import fs from 'node:fs';
import path from 'node:path';
import crypto from 'node:crypto';
import { fileURLToPath, pathToFileURL } from 'node:url';
import { validateUsagiWardrobe } from '../../src/capabilities/companion/presentation/usagi-raster-wardrobe.mjs';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '../..');
const assetRoot = path.join(root, 'assets/companion/usagi/wardrobe');
const specs = path.join(assetRoot, 'source-specs');
const hash = value => crypto.createHash('sha256').update(value).digest('hex');
const appearance = {}, authored = {}, sources = new Map();
function fittedEntry(original) {
  const entry = structuredClone(original);
  for (const [viewName, authoredView] of Object.entries(entry.views)) {
    const view = entry.runtimeFit?.overrides?.[viewName]
      ? structuredClone(entry.runtimeFit.overrides[viewName]) : authoredView;
    entry.views[viewName] = view;
    const fit = { ...entry.runtimeFit, ...entry.runtimeFit?.views?.[viewName] };
    const scale = fit.scale ?? 1, [dx, dy] = fit.translate || [0, 0];
    if (![scale, dx, dy].every(Number.isFinite) || scale <= 0 || scale > 1.5 || Math.abs(dx) > 8 || Math.abs(dy) > 8) {
      throw new Error(`invalid declared fit: ${entry.itemId}/${viewName}`);
    }
    if (scale === 1 && dx === 0 && dy === 0) continue;
    const sprites = [...view.back, ...view.front];
    if (!sprites.length) continue;
    if (scale !== 1 && sprites.some(sprite => sprite.bone !== 'root')) throw new Error('scaled garments need an explicit bone-anchor refit');
    const left = Math.min(...sprites.map(sprite => sprite.rect[0]));
    const right = Math.max(...sprites.map(sprite => sprite.rect[0] + sprite.rect[2]));
    const bottom = Math.max(...sprites.map(sprite => sprite.rect[1] + sprite.rect[3]));
    const center = (left + right) / 2;
    for (const sprite of sprites) {
      const [x, y, width, height] = sprite.rect;
      sprite.authoredRect = sprite.rect;
      sprite.rect = [center + (x - center) * scale + dx, bottom + (y - bottom) * scale + dy, width * scale, height * scale];
    }
  }
  return entry;
}
const fragments = fs.readdirSync(specs).filter(name => name.endsWith('.json')).sort()
  .map(file => ({ file, fragment: JSON.parse(fs.readFileSync(path.join(specs, file), 'utf8')) }))
  .sort((a, b) => Number(Boolean(a.fragment.replaces)) - Number(Boolean(b.fragment.replaces)) || a.file.localeCompare(b.file));
for (const { fragment } of fragments) {
  for (const [key, entry] of Object.entries(fragment.appearance)) {
    if (appearance[key] && fragment.replaces?.[key] !== hash(JSON.stringify(authored[key]))) {
      throw new Error(`duplicate wardrobe key without matching predecessor: ${key}`);
    }
    if (!appearance[key] && fragment.replaces?.[key]) throw new Error(`missing garment predecessor: ${key}`);
    authored[key] = entry;
    appearance[key] = fittedEntry(entry);
  }
  if (Object.keys(fragment.replaces || {}).some(key => !fragment.appearance[key])) throw new Error('unused garment replacement declaration');
}
for (const entry of Object.values(appearance)) {
    for (const view of Object.values(entry.views)) for (const sprite of [...view.back, ...view.front]) {
      const sourcePath = path.resolve(assetRoot, sprite.src);
      if (!sourcePath.startsWith(assetRoot + path.sep)) throw new Error(`outside wardrobe: ${sprite.src}`);
      const bytes = fs.readFileSync(sourcePath);
      if (bytes.subarray(0, 8).toString('hex') !== '89504e470d0a1a0a') throw new Error(`invalid PNG: ${sprite.src}`);
      const digest = hash(bytes);
      if (sprite.sha256 && digest !== sprite.sha256) throw new Error(`source hash changed: ${sprite.src}`);
      sources.set(sprite.src, { sha256: digest, decodedBytes: bytes.readUInt32BE(16) * bytes.readUInt32BE(20) * 4 });
    }
}
const records = [...sources].sort(([a], [b]) => a.localeCompare(b));
const digest = hash(JSON.stringify({ appearance, sources: records }));
const version = Math.max(1, Number.parseInt(digest.slice(0, 8), 16));
const data = { id: 'usagi-reference-wardrobe', version, assetDigest: digest,
  artBounds: { x: -15, y: -31, width: 96, height: 113 }, appearance,
  assetAccounting: { sourceCount: sources.size, decodedBytes: records.reduce((total, [, value]) => total + value.decodedBytes, 0) } };
const activeSprites = validateUsagiWardrobe({ ...data, baseUrl: pathToFileURL(assetRoot + path.sep).href });
data.assetAccounting.activeRasterSources = new Set(activeSprites.map(sprite => sprite.src)).size;
if (data.assetAccounting.decodedBytes > 48 * 1024 * 1024) throw new Error('wardrobe exceeds decoded cache budget');
const output = `// Generated by tools/usagi-wardrobe/assemble.mjs. Saved source hashes determine the version.\n`
  + `const data = ${JSON.stringify(data, null, 2)};\n`
  + `const freeze = value => { if (value && typeof value === 'object') { Object.values(value).forEach(freeze); Object.freeze(value); } return value; };\n`
  + `const USAGI_WARDROBE = freeze({ ...data, baseUrl: new URL('./', import.meta.url).href });\n`
  + `export { USAGI_WARDROBE };\n`;
const destination = path.join(assetRoot, 'usagi.wardrobe.mjs');
if (process.argv.includes('--check')) {
  if (!fs.existsSync(destination) || fs.readFileSync(destination, 'utf8') !== output) throw new Error('Usagi wardrobe manifest is stale');
} else fs.writeFileSync(destination, output);
console.log(JSON.stringify({ garments: Object.keys(appearance).length, ...data.assetAccounting, version, digest }));
