'use strict';
const test = require('node:test');
const assert = require('node:assert/strict');
const { createUnitOfWork, createBuyCompanionFoodWorkflow, createFeedCompanionWorkflow } = require('../src/application');
const { normalizePersistedState } = require('../src/platform/persistence/persisted-schema');
const { projectFoodShop } = require('../src/capabilities/companion/domain/food-shop');
const { buildRelationshipProjection } = require('../src/capabilities/companion/domain/relationship-projection');
const { FOODS } = require('../src/content/legacy-pet-content');
const NOW = Date.parse('2026-10-01T12:00:00');
test('every selectable form has an explicit favorite and favorite feeding finishes before celebration', async () => {
  const { SKINS } = require('../src/skins.mjs');
  const { FAVORITE_FOODS } = require('../src/content/food-progression.mjs');
  for (const id of Object.keys(SKINS)) assert.ok(FOODS[FAVORITE_FOODS[id]], id);
  const { createPetFeeding } = await import('../src/surfaces/pet/feeding.mjs');
  let now = 0; const events = []; const celebrations = [];
  const feeding = createPetFeeding({ client: { pet_feed() {} }, clock: { read: () => now }, present: event => events.push(event), onPresentationComplete: ms => celebrations.push(ms) });
  feeding.start('favorite'); now = 1400; feeding.advance();
  assert.equal(events.at(-1).expressionId, 'react.happy');
  assert.deepEqual(celebrations, []);
  now = 3500; feeding.advance();
  assert.deepEqual(celebrations, [4500]);
  feeding.start('favorite'); feeding.cancel(); now = 9000; feeding.advance();
  assert.deepEqual(celebrations, [4500]);
});
test('purchase gates protect tickets while existing stock stays feedable below its purchase level', () => {
  const { fixture } = require('../test-support/growth-food-fixture');
  const f = fixture(); const before = f.read();
  assert.equal(f.buy.execute(f.request('rice')).reason, 'food-locked'); assert.deepEqual(f.read(), before);
  f.edit(state => { state.level = 2; state.currentSkin = 'usagi'; });
  assert.equal(f.buy.execute(f.request('carrot')).ok, true);
  const result = f.feed.execute(f.request('carrot'));
  assert.equal(result.favorite, true); assert.equal(result.animation, 'favorite');
  assert.equal(f.read().pet.foodTickets, 5); assert.equal(f.read().xp, 0);
  f.edit(state => { state.pet.foodInventory.cake = 1; });
  assert.equal(f.feed.execute(f.request('cake')).ok, true);
  const projection = buildRelationshipProjection({ ...f.read(), foods: FOODS, now: NOW });
  assert.equal(projection.bondRoadmap.length, 3);
  assert.ok(projection.bondRoadmap.every(stage => stage.remaining > 0));
  assert.equal(projection.tastes.some(item => item.id === 'basic'), false);
});
test('new companions start with berries only; level changes reveal the same catalog without deleting old stock', () => {
  const state = normalizePersistedState({}, { now: NOW });
  assert.deepEqual(Object.entries(state.pet.foodInventory).filter(([,n]) => n > 0), [['berry',2]]);
  const low = projectFoodShop({ foods: FOODS, level: 1, foodTickets: 999, inventory: { cake: 2 } });
  assert.deepEqual(low.items.filter(item => item.unlocked).map(item => item.id), ['berry', 'carrot']);
  assert.equal(low.items.find(item => item.id === 'cake').inventory, 2);
  assert.equal(low.items.find(item => item.id === 'cake').affordable, false);
  const high = projectFoodShop({ foods: FOODS, level: 12, foodTickets: 999, currentSkin: 'ocean' });
  assert.ok(high.items.every(item => item.unlocked));
  assert.equal(high.items.find(item => item.favorite).id, 'fish');
});
