// App-authored interface copy only. User content and provider output are never catalog keys.
export const EN = Object.freeze({
  "补充要求或反馈": "Requests or feedback",
  "例如：每一步再小一点，先从不用出门的事开始": "For example: smaller steps, starting with something I can do at home",
  "继续讨论": "Discuss further",
  "选择日期": "Choose a date",
  "测试失败，请检查配置与网络": "Test failed. Check your configuration and network",
  "上一次测试尚未结束，请稍后重试": "The previous test is still ending. Try again shortly",
  "网络连接失败": "Network connection failed",
  "HTTPS 证书验证失败": "HTTPS certificate verification failed",
  "无法解析服务商地址": "Could not resolve the provider address",
  "API 未返回有效的模型文本": "API did not return valid model text",
  "测试已取消": "Test cancelled",
  "测试超时，请检查网络或稍后重试": "Test timed out. Check your network or try again later",
  "服务商拒绝了测试请求": "Provider rejected the test request",
  "服务商暂不可用": "Provider temporarily unavailable",
  "服务商限流或额度不足": "Provider rate limit or quota exceeded",
  "模型或 API 路径不可用": "Model or API route unavailable",
  "服务商拒绝访问，请检查密钥与模型权限": "Access denied. Check the API key and model permissions",
  "密钥认证失败": "API key authentication failed",
  "地址不可用：仅支持公网 HTTPS、443 端口": "Address unavailable: only public HTTPS on port 443 is supported",
  "地址已更改，请填写用于此地址的 API 密钥后测试": "The address changed. Enter its API key before testing",
  "请输入 API 密钥，或先导入已保存的密钥": "Enter an API key, or import a saved key first",
  "密钥格式无效": "Invalid API key format",
  "模型名称无效": "Invalid model name",
  "连接成功 · 模型已响应（{duration} 毫秒）": "Connected · Model responded ({duration} ms)",
  "正在测试当前输入…": "Testing current inputs…",
  "取消测试": "Cancel test",
  "测试连接": "Test connection",
  "测试当前输入，不保存配置；仅发送固定测试文字，可能产生少量费用。": "Tests your current inputs without saving. Sends only fixed test text; a small provider charge may apply.",
  "连接测试说明": "About connection testing",
  "提醒等级": "Reminder levels",
  "安排与能量": "Planning and energy",
  "本地辅助": "Local assistance",
  "专注与节奏": "Focus and rhythm",
  "活动跟随": "Activity companion",
  "伙伴与动效": "Companion and motion",
  "小步": "bubu",
  "像素兽": "Pixel companion",
  "小步 v0.0.2-dev.2": "bubu v0.0.2-dev.2",
  "现在": "Now",
  "安排": "Plan",
  "回顾": "Review",
  "任务": "Tasks",
  "日常": "Routines",
  "收件箱": "Inbox",
  "已归档": "Archived",
  "伙伴": "Companion",
  "设置": "Settings",
  "主要区域": "Main navigation",
  "打开设置": "Open settings",
  "关闭设置": "Close settings",
  "免打扰": "Do not disturb",
  "切换免打扰": "Toggle do not disturb",
  "关闭免打扰": "Turn off do not disturb",
  "开启免打扰": "Turn on do not disturb",
  "休息中": "On a break",
  "专注中": "Focusing",
  "已暂停": "Paused",
  "待机": "Idle",
  "知道了，不再提醒：{message}": "Dismiss notice: {message}",
  "换一件": "Switch task",
  "有点卡": "Feeling stuck",
  "关闭候选": "Close suggestions",
  "调整": "Adjust",
  "暂停": "Pause",
  "继续": "Resume",
  "结束这段": "End session",
  "结束这段计时": "End this timer",
  "继续计时": "Resume timer",
  "先做两分钟": "Start with two minutes",
  "计时等待核对": "Timer needs review",
  "这一轮已到点，等待确认计入完成": "Time is up. Confirm completion.",
  "休息已暂停": "Break paused",
  "放弃本轮": "Discard session",
  "确认计入完成": "Confirm completion",
  "放弃本轮，不发完成奖励": "Discard session without a completion reward",
  "确认本轮计入完成": "Confirm this session as completed",
  "开始专注": "Start focus",
  "开始自由专注": "Start free focus",
  "尚未开始": "Not started",
  "本轮时长": "Session duration",
  "这一段": "This session",
  "本轮计时进度": "Session progress",
  "这一轮时长减少 5 分钟": "Reduce session by 5 minutes",
  "这一轮时长增加 5 分钟": "Extend session by 5 minutes",
  "选择专注分钟数": "Choose focus duration in minutes",
  "常用时长": "Duration presets",
  "完成当前任务": "Complete current task",
  "完成这件": "Complete task",
  "编辑当前任务": "Edit current task",
  "编辑": "Edit",
  "加一步": "Add a step",
  "额外的小步骤": "Additional small step",
  "接下来需要做的小步骤": "The next small step",
  "添加": "Add",
  "取消": "Cancel",
  "今天": "Today",
  "能量": "Energy",
  "休息一下": "Take a break",
  "自由专注": "Free focus",
  "还没有选定任务": "No task selected yet",
  "放松片刻，给自己一点空隙": "A moment to relax and take a breath",
  "这一段时间，留给手边的事": "This time is for what is in front of you",
  "先选定一件事，两分钟才有落点。": "Choose a task for your two-minute start.",
  "先用“换个更小的下一步”写下落点。": "Write a next action with “Find a smaller next step”.",
  "已完成步骤": "Completed step",
  "只读步骤": "Read-only step",
  "完成步骤": "Complete step",
  "适合现在": "Good for now",
  "容易开始": "Easy to start",
  "优先考虑": "Worth prioritizing",
  "能量、时长和启动成本": "Energy, duration, and effort to get started",
  "切换未完成，请再试一次。": "The task was not switched. Try again.",
  "暂无可切换的任务。": "No other tasks available.",
  "暂时无法读取任务，请再试一次。": "Tasks could not be loaded. Try again.",
  "从一件小事开始": "Start with something small",
  "眼前这一步": "The next small step",
  "正在进行": "In progress",
  "随时可以接着来": "Ready when you are",
  "为下次留个入口": "Leave a place to pick up next time",
  "打开材料，只做第一小步": "Open what you need and take one small step",
  "这一段，留给手边的事": "This time is for what is in front of you",
  "从任务里换一件来做": "Choose a task to work on",
  "把脑中的一件事放下来": "Write down one thing on your mind",
  "这件事已经做完了": "This task is complete",
  "卡在：{blocker}": "Stuck on: {blocker}",
  "两分钟内只做：{action}": "For two minutes, just: {action}",
  "换成{title}": "Switch to {title}",
  "排序依据：{summary}": "Based on: {summary}",
  "为当前任务“{title}”专注 {minutes} 分钟": "Focus on “{title}” for {minutes} minutes",
  "开始不关联任务的 {minutes} 分钟自由专注": "Start {minutes} minutes of free focus without a task",
  "{minutes} 分钟待启动": "{minutes} minutes, ready to start",
  "当前时间 {time}": "Current time {time}",
  "剩余 {minutes} 分 {seconds} 秒": "{minutes} minutes and {seconds} seconds remaining",
  "已完成 {percent}%": "{percent}% complete",
  "{minutes} 分钟": "{minutes} min",
  "已经投入 {minutes} 分钟，不能缩到这之下": "Already spent {minutes} minutes; the session cannot be shorter",
  "时长未保存，请重试": "Duration was not saved. Try again.",
  "开": "On",
  "关": "Off",
  "通用": "General",
  "外观": "Appearance",
  "界面语言": "Language",
  "跟随系统": "System",
  "中文": "Chinese",
  "英文": "English",
  "深色": "Dark",
  "浅色": "Light",
  "感官负荷": "Sensory comfort",
  "动效强度": "Motion",
  "减少": "Reduced",
  "平衡": "Balanced",
  "完整": "Full",
  "视觉刺激": "Visual stimulation",
  "低": "Low",
  "中": "Medium",
  "高": "High",
  "伙伴主动程度": "Companion activity",
  "关闭": "Close",
  "安静": "Quiet",
  "活泼": "Lively",
  "提醒声音": "Reminder sounds",
  "伙伴跟着你": "Activity companion",
  "跟着当前活动": "Follow current activity",
  "了解跟着当前活动": "About following current activity",
  "根据前台应用、播放器音频输出和已接入 AI 工具的事件切换陪伴状态。不读取窗口标题、歌名或对话内容，不保存，也不发送。": "The companion follows the foreground app, music-player audio output, and events from connected AI tools. Window titles, song names, and conversation content are never read, saved, or sent.",
  "接入 AI 工具": "Connect AI tools",
  "在你用的 AI 工具里装上随附的 bubu-companion 插件，提问和回答时伙伴会立刻切到“和 AI 对话”。插件只通知“提问了 / 回答完了”，不带提问、回答或文件内容；收到过信号的工具会在这里显示。": "Install the included bubu-companion plugin in your AI tool to show an AI-chat pose while you ask and receive answers. It sends only “question sent / answer finished”, without questions, answers, or file contents. Tools that have sent a signal appear here.",
  "时间与节奏": "Time and rhythm",
  "一天的作息": "Daily schedule",
  "上班时间": "Work starts",
  "下班时间": "Work ends",
  "点": "h",
  "到点收工提醒": "End-of-work reminder",
  "临时任务默认时效": "Temporary task expiry",
  "当天 24 点": "Midnight today",
  "6 小时": "6 hours",
  "12 小时": "12 hours",
  "24 小时": "24 hours",
  "48 小时": "48 hours",
  "72 小时": "72 hours",
  "工作时间用在哪": "How work hours are used",
  "专注与休息": "Focus and breaks",
  "专注时长": "Focus duration",
  "休息时长": "Break duration",
  "分钟": "min",
  "专注途中软提醒": "Gentle focus reminders",
  "空闲喝水/站立提醒": "Water and stretch reminders when idle",
  "提醒与免打扰": "Reminders and quiet time",
  "免打扰模式": "Do not disturb",
  "提醒角色": "Reminder character",
  "专注中最高提醒": "Maximum reminder during focus",
  "休息期最高提醒": "Maximum reminder during breaks",
  "/ 4 级": "/ 4 levels",
  "测试休息提醒": "Test break reminder",
  "测试专注提醒": "Test focus reminder",
  "提醒等级说明": "Reminder levels explained",
  "辅助能力": "Assistance",
  "本地策略建议": "Local strategy suggestions",
  "收尾与启动回顾": "Completion and start reviews",
  "快捷键": "Keyboard shortcuts",
  "闪念快捷键": "Quick capture shortcut",
  "组合键": "Key combination",
  "能量曲线": "Energy curve",
  "显示能量曲线": "Show energy curve",
  "校准": "Calibration",
  "重置校准": "Reset calibration",
  "真的重置": "Confirm reset",
  "没能重置，稍后再试。": "Could not reset. Try again later.",
  "已丢掉学到的参数，曲线回到未校准的样子。": "Learned adjustments were removed. The curve is uncalibrated again.",
  "本来就没学过什么，没有可丢的。": "There were no learned adjustments to remove.",
  "曲线关着：今天页和时间线都不画它，也不再学你的作息。": "The curve is off. It is hidden from Today and the timeline, and no longer learns your routine.",
  "已按你的 {count} 次自评微调过这条曲线。": "This curve has been adjusted using {count} self-ratings.",
  "校准进度 {count}/10 次自评": "Calibration: {count}/10 self-ratings",
  "正在保存…": "Saving…",
  "已保存并生效": "Saved and applied",
  "未保存，请重试": "Not saved. Try again.",
  "设置已保存；{warning}": "Settings saved; {warning}",
  "不发往公网": "Nothing is sent to the public internet",
  "出网字段：{fields}": "Fields sent: {fields}",
  "{outbound} · 密钥只存系统安全存储": "{outbound} · Keys stay in system secure storage",
  "本机数据已保存到数据库。兼容文件待同步或存在外部修改，完整备份不能只复制 config.json。": "Local data is saved in the database. The compatibility file is awaiting sync or has external changes; copying config.json alone is not a complete backup.",
  "安排偏好与曲线试用": "Planning preferences and curve trials",
  "应用更新": "App updates",
  "自动检查更新": "Check for updates automatically",
  "检查更新": "Check for updates",
  "下载": "Download",
  "取消下载": "Cancel download",
  "重启更新": "Restart to update",
  "重启前，请先保存尚未提交的输入。现在重启？": "Save any unsubmitted input before restarting. Restart now?",
  "暂不重启": "Not now",
  "重启安装": "Restart and install",
  "AI 助手": "AI assistant",
  "启用 AI": "Enable AI",
  "连接模型": "Model connection",
  "模型名称": "Model name",
  "输入服务商的模型名称": "Enter your provider's model name",
  "服务地址": "Service URL",
  "了解服务地址": "About the service URL",
  "使用 OpenAI 兼容接口。填 HTTPS 地址，留空使用官方默认地址。": "Use an OpenAI-compatible API. Enter an HTTPS URL, or leave blank for the official default.",
  "OpenAI 兼容 HTTPS 接口": "OpenAI-compatible HTTPS API",
  "API 密钥": "API key",
  "留空保留已保存密钥": "Leave blank to keep the saved key",
  "密钥保存在系统安全存储，保存后不回显。": "Keys are saved in system secure storage and are never shown after saving.",
  "保存配置": "Save configuration",
  "密钥管理": "Key management",
  "从环境变量导入": "Import from environment variable",
  "清除密钥": "Clear key",
  "使用范围": "Usage scope",
  "聊两句": "Talk it through",
  "了解聊两句": "About talking it through",
  "新建任务时，通过问答理清下一步；只发送你在对话里输入的内容。": "Clarify a next step through conversation when creating a task. Only what you type in the conversation is sent.",
  "闪念校准能量": "Use captures for energy calibration",
  "了解闪念校准能量": "About capture-based energy calibration",
  "发送刚保存的闪念，仅明确的当前状态用于短期校准。": "Sends the capture just saved. Only explicit descriptions of your current state are used for short-term calibration.",
  "整理随手记": "Organize quick notes",
  "了解整理随手记": "About organizing quick notes",
  "发送刚保存的一句，建议转任务、日常或状态，确认后才应用。": "Sends the note just saved and suggests a task, routine, or status. Changes apply only after confirmation.",
  "伙伴 AI 用餐建议": "AI meal suggestions for your companion",
  "了解伙伴 AI 用餐建议": "About AI companion meal suggestions",
  "默认关闭。伙伴会按本地规则自动用餐；开启本项和 AI 总开关并配置模型、密钥后，可将角色、饱食、餐次、可用食物和喜好发送给所选 Provider。每天最多 3 次，每次最多等待 5 秒；失败按本地规则用餐。不发送任务、情绪、用药、随手记、桌面或聊天内容。": "Off by default. The companion eats automatically using local rules. With this option and AI enabled, plus a configured model and key, character, fullness, meal, available food, and preferences may be sent to the selected provider. Up to 3 requests daily, each with a 5-second timeout; local rules are used on failure. Tasks, mood, medication, quick notes, desktop content, and chats are not sent.",
  "数据与隐私": "Data and privacy",
  "带上长期记忆": "Include long-term memory",
  "AI 记得什么": "What AI remembers",
  "刷新": "Refresh",
  "候选内容不会自动成为记忆。带上长期记忆的开关仍单独控制发送。": "Suggestions do not become memories automatically. Sending still depends on the separate long-term memory setting.",
  "有效": "Active",
  "待确认": "Awaiting confirmation",
  "暂停使用": "Paused",
  "已移除": "Removed",
  "记忆状态": "Memory status",
  "更多记忆": "More memories",
  "记一件事": "Remember something",
  "随手记": "Quick note",
  "记录闪念": "Capture a thought",
  "记下一句话…": "Write a quick note…",
  "保存随手记": "Save quick note",
  "收下并关闭": "Save and close",
  "快捷行动": "Quick actions",
  "当前执行": "Current session",
  "接下来": "Next",
  "追加子步骤": "Add a step",
  "追加一个可以立刻做的小步骤…": "Add a small step you can do now…",
  "追加": "Add",
  "完成任务": "Complete task",
  "结束": "End",
  "待启动任务": "Tasks ready to start",
  "轻轻开始": "Start small",
  "下一动作": "Next action",
  "接下来能做的一小步": "One small step you can take next",
  "例如：打开笔记，写下第一行": "For example: open your notes and write the first line",
  "开始 2 分钟": "Start 2 minutes",
  "快速记录": "Quick capture",
  "记下来就回去，稍后在收件箱处理。": "Write it down and return to what you were doing. Sort it in the inbox later.",
  "进行中": "In progress",
  "先留下一句话。": "Start with a quick note.",
  "写下一步，开始 2 分钟": "Write a next step and start 2 minutes",
  "先做 2 分钟": "Start with 2 minutes",
  "仍然完成": "Complete anyway",
  "记好了": "Saved",
  "还有 {count} 个步骤没勾；再按一次确认完成。": "{count} steps are still unchecked. Press again to confirm completion.",
  "几": "a few",
  "剩余 {remaining}，已投入 {elapsed}": "{remaining} remaining; {elapsed} spent",
  "当前状态暂时不可用，仍可快速记录。": "Current status is unavailable. You can still capture a note.",
  "这次没有完成，请再试一次。": "That did not complete. Try again.",
  "状态已经变化，请检查主面板后再试。": "The state has changed. Check the main panel and try again.",
  "这件任务已经不在当前清单里。": "This task is no longer in the current list.",
  "这件任务已经完成。": "This task is complete.",
  "预约时间还没到，暂时不能继续计时。": "The scheduled time has not arrived. The timer cannot resume yet.",
  "计时已换成另一轮，请按更新后的面板继续。": "A different session is now active. Continue from the updated panel.",
  "计时状态已变化，请重新查看继续或确认按钮。": "The timer state changed. Check the resume or confirmation button again.",
  "计时状态暂不可用，请重新打开面板。": "The timer state is unavailable. Reopen the panel.",
  "这轮计时的恢复状态不一致，暂时不能继续或确认；可以放弃本轮。": "This session's recovery state is inconsistent. It cannot be resumed or confirmed, but can be discarded.",
  "这件任务已经过期，请到主面板决定是否续期。": "This task has expired. Decide whether to extend it in the main panel.",
  "这一次已经跳过。": "This occurrence was skipped.",
  "已有一段计时正在进行。": "A timer is already active.",
  "这段计时已经在运行。": "This timer is already running.",
  "当前没有可操作的计时。": "There is no active timer to change.",
  "当前计时没有暂停。": "The current timer is not paused.",
  "上一轮已到点，请到主面板确认。": "The previous session ended. Confirm it in the main panel.",
  "两分钟已结束，请先到主面板选择下一步。": "Your two minutes are up. Choose the next step in the main panel.",
  "请先到主面板保存或跳过上一轮落点。": "Save or skip the last session's handoff note in the main panel first.",
  "状态刚刚变了，请再试一次。": "The state just changed. Try again.",
  "任务内容已变化；输入仍保留，取消后可重新选择。": "The task changed. Your input is kept; cancel to select it again.",
  "这件任务已有下一动作，请重新选择后开始。": "This task already has a next action. Select it again to start.",
  "这件任务还需要一个明确的下一动作。": "This task needs a clear next action.",
  "两分钟启动结果暂不可用，请到主面板核对。": "The two-minute start result is unavailable. Check the main panel.",
  "步骤已达上限，当前输入还在；请先到主面板整理步骤。": "The step limit was reached. Your input is kept; organize the steps in the main panel first.",
  "下一动作或任务版本无效，输入内容还在。": "The next action or task version is invalid. Your input is kept.",
  "正在读取生效的组合…": "Reading the active shortcut…",
  "已关闭。仍可用伙伴右键菜单里的快速记录": "Off. Quick capture is still available in the companion's right-click menu.",
  "这台机器上的组合键都被占用了。仍可用伙伴右键菜单里的快速记录，或从菜单栏打开": "All shortcut combinations are in use. Open quick capture from the companion's right-click menu or the menu bar.",
  "现在生效：{shortcut} · 你设的 {configured} 被别的程序占着,先用这个": "Active: {shortcut}. Your chosen {configured} is in use by another app, so this is used for now.",
  "（配置没被改掉,那个程序关掉后会自己回来）": " (Your setting is unchanged and will return when that app closes.)",
  "现在生效：{shortcut}": "Active: {shortcut}",
  "快捷行动 {shortcut}": "Quick actions {shortcut}",
  "打开快捷行动面板": "Open quick actions",
  "打开快捷行动面板，快捷键 {shortcut}": "Open quick actions, shortcut {shortcut}",
  "按 {shortcut} 随时记下闪念": "Press {shortcut} to capture a thought anytime",
  "用伙伴右键菜单里的快速记录随时记下闪念": "Capture a thought anytime from the companion's right-click menu",
  "按下想用的组合…": "Press your preferred shortcut…",
  "未设置": "Not set",
  "Esc 取消 · 至少要带一个修饰键（⌘ ⌃ ⌥ ⇧）": "Esc to cancel · Include a modifier (⌘ ⌃ ⌥ ⇧)",
  "正在绑定 {shortcut}…": "Binding {shortcut}…",
  "这个键不能用于全局快捷键 · 请用字母、数字、F1–F24 或空格等按键": "This key cannot be used globally. Use a letter, number, F1–F24, or Space.",
  "至少要带一个修饰键（⌘ ⌃ ⌥ ⇧）· Esc 取消": "Include a modifier (⌘ ⌃ ⌥ ⇧) · Esc to cancel",
  "小步 桌面宠物：点按与按住都是互动，右键打开命令菜单": "bubu desktop companion: click or hold to interact; right-click for commands",
  "伙伴当前动作": "Current companion activity",
  "换一个陪伴动作": "Choose another companion activity",
  "切换伙伴当前动作": "Change companion activity",
  "喂它吃东西": "Feed your companion",
  "打开喂食": "Open food menu",
  "伙伴命令": "Companion commands",
  "打开面板": "Open panel",
  "隐藏伙伴": "Hide companion",
  "喂食": "Feed",
  "关闭喂食面板": "Close food menu",
  "宠物饱食度": "Companion fullness",
  "核对上次喂食结果": "Check the previous feeding result",
  "今日已用完": "Used up today",
  "免费 · 饱食最多到 {value}": "Free · Fullness up to {value}",
  "饱食不高于 {value} 时可用": "Available at fullness {value} or below",
  "今日余 {count}": "{count} left today",
  "饱食 {value}/100": "Fullness {value}/100",
  "上轮已经到点，请在面板确认计入完成或放弃本轮": "The previous session ended. Confirm completion or discard it in the panel.",
  "两分钟已经完成，请先在面板选择下一步": "Your two minutes are complete. Choose the next step in the panel.",
  "先保存或跳过上一轮的落点，再开始新一轮": "Save or skip the previous handoff note before starting another session.",
  "上班时间减少 1 小时": "Reduce work start by 1 hour",
  "上班时间增加 1 小时": "Increase work start by 1 hour",
  "下班时间减少 1 小时": "Reduce work end by 1 hour",
  "下班时间增加 1 小时": "Increase work end by 1 hour",
  "专注时长减少 5 分钟": "Reduce focus duration by 5 minutes",
  "专注时长增加 5 分钟": "Increase focus duration by 5 minutes",
  "休息时长减少 1 分钟": "Reduce break duration by 1 minute",
  "休息时长增加 1 分钟": "Increase break duration by 1 minute",
  "专注途中软提醒间隔减少 5 分钟": "Reduce focus reminder interval by 5 minutes",
  "专注途中软提醒间隔增加 5 分钟": "Increase focus reminder interval by 5 minutes",
  "空闲喝水和站立提醒间隔减少 15 分钟": "Reduce water and stretch reminder interval by 15 minutes",
  "空闲喝水和站立提醒间隔增加 15 分钟": "Increase water and stretch reminder interval by 15 minutes",
  "专注中最高提醒降低 1 级": "Reduce maximum focus reminder by one level",
  "专注中最高提醒提高 1 级": "Increase maximum focus reminder by one level",
  "休息期最高提醒降低 1 级": "Reduce maximum break reminder by one level",
  "休息期最高提醒提高 1 级": "Increase maximum break reminder by one level",
  "测试休息提醒 L1": "Test break reminder L1",
  "测试休息提醒 L2": "Test break reminder L2",
  "测试休息提醒 L3": "Test break reminder L3",
  "测试休息提醒 L4": "Test break reminder L4",
  "测试专注提醒 L1": "Test focus reminder L1",
  "测试专注提醒 L2": "Test focus reminder L2",
  "测试专注提醒 L3": "Test focus reminder L3",
  "测试专注提醒 L4": "Test focus reminder L4",
  "语言": "Language",
  "界面主题": "Interface theme",
  "输入已收起；已发送的启动仍会按原任务处理。": "Input closed. The start already sent will still apply to its original task.",
  "任务状态已变化；输入仍保留，取消后可重新选择。": "The task state changed. Your input is kept; cancel to select it again.",
  "下一动作需要 1–200 个字，输入内容还在。": "The next action needs 1–200 characters. Your input is kept.",
  "两分钟启动暂不可用，请重新打开面板。": "The two-minute start is unavailable. Reopen the panel.",
  "两分钟已开始。": "Your two minutes have started.",
  "两分钟已开始；窗口未能关闭，可以继续计时。": "Your two minutes have started. The window could not close; the timer can continue here.",
  "修改未完成步骤": "Edit unfinished step",
  "保存": "Save",
  "修改": "Edit",
  "完成步骤：{title}": "Complete step: {title}",
  "下一小步，随时补上。": "Add the next small step anytime.",
  "已同步": "Synced",
  "今天的能量曲线": "Today's energy curve",
  "今天几点起的？": "What time did you wake up today?",
  "今天几点起的": "Today's wake-up time",
  "6点": "6 am",
  "7点": "7 am",
  "8点": "8 am",
  "9点": "9 am",
  "10点": "10 am",
  "11点后": "After 11 am",
  "跳过": "Skip",
  "很低": "Very low",
  "一般": "Okay",
  "好": "Good",
  "很好": "Very good",
  "现在感觉怎么样，五档自评": "How you feel now, on a five-point scale",
  "刚做了": "Just did",
  "管理日常": "Manage routines",
  "任务列表": "Task list",
  "可做": "Ready",
  "现在就能开始的": "Ready to start now",
  "计划在今天，或今天这一次的重复任务": "Planned for today, or today's recurring task",
  "重复": "Recurring",
  "属于某个重复系列": "Part of a recurring series",
  "有截止": "Has a deadline",
  "带外部截止时间": "Has an external deadline",
  "等待中": "Waiting",
  "预约未到、已过期或已跳过": "Scheduled for later, expired, or skipped",
  "已完成": "Completed",
  "已完成（只读）": "Completed (read-only)",
  "任务筛选": "Task filters",
  "新建任务": "New task",
  "标签筛选": "Tag filters",
  "这个筛选下没有任务": "No tasks match this filter",
  "没有任务": "No tasks",
  "待整理": "To sort",
  "历史记录": "History",
  "收件范围": "Inbox scope",
  "全部留存": "Keep all",
  "全部分类": "All categories",
  "按收件分类筛选": "Filter inbox by category",
  "重试读取": "Retry loading",
  "重试删除": "Retry deletion",
  "没有待整理的收件": "Nothing waiting to be sorted",
  "随手记下的内容会留在这里": "Your quick notes will appear here",
  "加载更早记录": "Load earlier records",
  "已归档的任务": "Archived tasks",
  "今天的记录": "Today's records",
  "新建日常": "New routine",
  "日常详情": "Routine details",
  "日常名称": "Routine name",
  "想记住哪件小事？": "What small thing would you like to remember?",
  "类型：": "Type:",
  "日常类型": "Routine type",
  "例如：家务、宠物照料": "For example: chores, pet care",
  "类型名称": "Type name",
  "重复：": "Repeat:",
  "不提醒（手动记）": "No reminder (log manually)",
  "每天": "Daily",
  "工作日": "Weekdays",
  "每周": "Weekly",
  "手动记": "Log manually",
  "选星期": "Choose days",
  "重复频率": "Repeat frequency",
  "在：": "On:",
  "一": "Mon",
  "二": "Tue",
  "三": "Wed",
  "四": "Thu",
  "五": "Fri",
  "六": "Sat",
  "日": "Sun",
  "每周哪几天": "Days of the week",
  "提醒时间": "Reminder times",
  "早上 8:00": "8:00 am",
  "中午 12:00": "12:00 pm",
  "晚上 21:00": "9:00 pm",
  "选时间": "Choose a time",
  "轻提示": "Gentle prompt",
  "宠物气泡": "Companion bubble",
  "气泡与提醒卡片": "Bubble and reminder card",
  "提醒方式": "Reminder style",
  "添加日常": "Add routine",
  "提醒设置": "Reminder settings",
  "日常提醒": "Routine reminders",
  "已开启": "Enabled",
  "总专注": "Total focus",
  "任务完成": "Tasks completed",
  "回来的次数": "Times you returned",
  "专注轮次": "Focus sessions",
  "待回顾": "Awaiting review",
  "最近 12 周": "Last 12 weeks",
  "最近 12 周每日专注时长和任务完成数，点一天查看时间线": "Daily focus time and completed tasks over the last 12 weeks. Select a day to view its timeline.",
  "少": "Less",
  "多": "More",
  "当天完成数": "Completed that day",
  "这一天": "This day",
  "当天按时间排开的记录，点一条查看详情": "The day's records in time order. Select one for details.",
  "统计和时间线有什么区别": "How statistics and the timeline differ",
  "曲线为能量估计；点击活动查看详情。": "The curve estimates energy. Select an activity for details.",
  "当前等级经验值": "Experience points for the current level",
  "默契": "Bond",
  "伙伴默契进度": "Companion bond progress",
  "进度一直保留，按自己的节奏来。": "Progress stays with you. Go at your own pace.",
  "换形态": "Change form",
  "换装": "Outfits",
  "食物图鉴": "Food collection",
  "一起走过": "Our journey",
  "关闭待回顾": "Close pending reviews",
  "没有待回顾内容": "No pending reviews",
  "关闭食物图鉴": "Close food collection",
  "升级解锁新口味。兑换后，在桌宠旁喂食。": "Level up to unlock new flavors. Redeem food, then feed it from your desktop companion.",
  "食物如何获得": "How to get food",
  "兑换消耗 XP，不会降级。每天完成第一件任务赠送一颗浆果。已有库存一直保留。": "Redeeming food costs XP without lowering your level. The first completed task each day earns a berry. Your inventory is kept.",
  "关闭一起走过": "Close our journey",
  "默契里程碑": "Bond milestones",
  "按斜杠键聚焦输入框": "Press slash to focus the input",
  "聚焦输入框快捷键：斜杠键": "Focus input shortcut: slash",
  "记下一句，稍后整理": "Write a quick note to sort later",
  "收下这一句": "Save this note",
  "关闭换形态": "Close form selection",
  "桌宠种类": "Companion type",
  "该桌宠的解锁形象": "Unlocked looks for this companion",
  "恢复默认": "Reset to default",
  "关闭换装": "Close outfits",
  "配饰槽位": "Accessory slots",
  "每项修改单独预览、确认。": "Preview and confirm each change separately.",
  "重新读取": "Reload",
  "安排偏好": "Planning preferences",
  "来自对话的安排建议，确认后保存。": "A planning suggestion from your conversation, saved only after confirmation.",
  "偏好": "Preference",
  "新增偏好": "New preference",
  "开始时间": "Start time",
  "结束时间": "End time",
  "这个时段更想安排": "Preferred activities for this time",
  "轻一些的事": "Lighter tasks",
  "一般难度的事": "Moderate tasks",
  "需要更多投入的事": "Tasks requiring more effort",
  "有效期": "Duration",
  "七天": "Seven days",
  "保存为偏好": "Save as a preference",
  "查看变更": "Preview changes",
  "撤销上次偏好变更": "Undo last preference change",
  "本机自评记录": "Local self-rating history",
  "默认关闭。开启后在本机保存新的自评和当时的估计；关闭不会清除已有记录。": "Off by default. When enabled, new self-ratings and their estimates are saved on this device. Turning it off keeps existing records.",
  "保留新的自评记录，仅保存在本机": "Keep new self-ratings on this device only",
  "清除已有的自评历史": "Clear existing self-rating history",
  "查看记录范围": "Preview record scope",
  "曲线试用": "Curve trial",
  "曲线是非医学日常估计，试用效果尚待观察。": "The curve is a non-medical estimate for daily planning. The trial's usefulness is still being evaluated.",
  "试用条件与范围": "Trial requirements and scope",
  "至少 10 条自评、覆盖 7 个日期且跨度满 7 天。每次只调整一个参数，幅度不超过可编辑范围的 2%；可在保存前比较曲线。": "Requires at least 10 self-ratings across 7 dates spanning at least 7 days. Each trial changes one parameter by no more than 2% of its editable range. Compare the curves before saving.",
  "参数": "Parameter",
  "曲线时段偏移": "Curve time offset",
  "上午上升时长": "Morning rise duration",
  "试用值（分钟）": "Trial value (minutes)",
  "试用期限": "Trial duration",
  "比较当前与建议曲线": "Compare current and suggested curves",
  "结束试用并恢复": "End trial and restore",
  "变更预览": "Change preview",
  "确认保存": "Confirm and save",
  "类别": "Category",
  "节律": "Rhythm",
  "背景": "Context",
  "卡点": "Sticking point",
  "完成模式": "Completion pattern",
  "关于什么": "Subject",
  "内容": "Content",
  "适用范围": "Scope",
  "工作": "Work",
  "个人": "Personal",
  "有效至（留空表示不设到期）": "Valid until (blank for no expiry)",
  "隐私范围": "Privacy scope",
  "普通，可在授权后参考": "Standard; may be used with permission",
  "敏感，仅在本机保留": "Sensitive; kept on this device only",
  "查看保存差异": "Preview changes before saving",
  "取消编辑": "Cancel editing",
  "已有记忆替换选择": "Choose an existing memory to replace",
  "记忆变更核对": "Review memory changes",
  "永久移除无法从应用内撤销。下列记忆、旧版本与相关派生内容会一并处理；相关来源不能再用于模型上下文。": "Permanent removal cannot be undone in the app. The listed memories, older versions, and related derived content are included. Their sources can no longer be used as model context.",
  "来源对话仍可能按原设置保留在本机。此操作不能删除已发送给外部模型服务商的副本。": "Source conversations may remain on this device according to their retention settings. This cannot delete copies already sent to external model providers.",
  "已核对影响范围和无法撤销的限制": "I reviewed the scope and understand this cannot be undone",
  "保留原状": "Keep unchanged",
  "查看撤销差异": "Preview undo changes",
  "刷新回执": "Refresh receipt",
  "记忆提交回执": "Memory change receipt",
  "核对这次确认的结果": "Check this confirmation's result",
  "拆成几步": "Break into steps",
  "关闭拆解任务对话框": "Close task breakdown dialog",
  "确认后添加到现有步骤。": "Added to the existing steps after confirmation.",
  "+ 加一步": "+ Add a step",
  "这次修改：": "Apply changes to:",
  "仅本次": "This time only",
  "本次及以后": "This and future occurrences",
  "拆解修改范围": "Scope of breakdown changes",
  "不用了": "No thanks",
  "加到步骤里": "Add to steps",
  "卡在哪？": "What's getting in the way?",
  "关闭卡住了对话框": "Close help dialog",
  "哪里卡住了？": "Where are you stuck?",
  "和 AI 一起理一理": "Work it through with AI",
  "不清楚": "Unclear",
  "太大": "Too big",
  "无聊": "Boring",
  "有压力": "Stressful",
  "没电": "Low energy",
  "被打断": "Interrupted",
  "选择卡点": "Choose a sticking point",
  "换个更小的下一步": "Find a smaller next step",
  "会改这件任务的下一步": "Changes this task's next step",
  "试个小办法": "Try a small strategy",
  "只给一句话，不动任务": "A brief suggestion; the task stays unchanged",
  "只做第一步（2 分钟）": "Take the first step (2 min)",
  "更小的下一步": "A smaller next step",
  "换一个": "Try another",
  "保留原样": "Keep as is",
  "用这个": "Use this",
  "为什么": "Why",
  "有用": "Helpful",
  "不合适": "Not a fit",
  "新任务": "New task",
  "关闭新任务对话框": "Close new task dialog",
  "填写任务名称即可保存，其他选项可稍后编辑。": "A task name is enough to save. Other details can be edited later.",
  "要做什么": "What would you like to do?",
  "想做什么？": "What would you like to do?",
  "计划在今天看到它": "Show it in today's plan",
  "明天": "Tomorrow",
  "计划在明天看到它": "Show it in tomorrow's plan",
  "不指定": "Unspecified",
  "不绑到某一天": "Not assigned to a specific day",
  "什么时候做": "When to do it",
  "添加步骤": "Add a step",
  "步骤": "Steps",
  "拆成步骤": "Break into steps",
  "AI 协作": "Work with AI",
  "建议填入草稿，保存后生效": "Suggestions enter the draft and apply after saving",
  "任务助手说明": "About task assistance",
  "建议只填入草稿，确认保存后才会生效。": "Suggestions only enter the draft. They apply after you confirm and save.",
  "更多选项": "More options",
  "备注": "Notes",
  "可选：补充背景或完成标准": "Optional: add context or a definition of done",
  "不重复": "Does not repeat",
  "只做一次": "One time only",
  "每天一次，完成后自动排下一次": "Daily; the next occurrence is scheduled after completion",
  "按选定的星期重复": "Repeats on selected weekdays",
  "每月": "Monthly",
  "每月同一天，月小自动夹到最后一天": "The same day each month, or the last day of a shorter month",
  "重复规则": "Recurrence rule",
  "星期：": "Days:",
  "每周重复的星期": "Days of the week to repeat",
  "下一次：": "Next occurrence:",
  "按日历": "By calendar",
  "按日历走，漏了不补债": "Follows the calendar without accumulating missed occurrences",
  "完成后再算": "After completion",
  "从完成那天开始重新计算": "Count from the completion date",
  "下一次什么时候排": "When to schedule the next occurrence",
  "每隔：": "Every:",
  "个周期": "cycles",
  "日期": "Dates",
  "截止：": "Deadline:",
  "清除": "Clear",
  "可开始：": "Available from:",
  "放在哪天：": "Planned date:",
  "能量、估时与标签": "Energy, estimate, and tags",
  "自动失效：": "Automatic expiry:",
  "不开启": "Off",
  "默认不开：没做完不应该自动变成一条过期提醒": "Off by default: unfinished tasks should not automatically become expiry reminders",
  "按设置": "Use settings",
  "跟随设置里的默认时效": "Uses the default expiry in settings",
  "今晚24点": "Midnight tonight",
  "明晚24点": "Midnight tomorrow",
  "自动失效": "Automatic expiry",
  "能量：": "Energy:",
  "自动": "Automatic",
  "根据任务标题自动推断": "Estimated from the task title",
  "任务所需能量": "Energy required for this task",
  "估时（分钟）：": "Estimate (minutes):",
  "标签：": "Tags:",
  "逗号分隔，最多 8 个": "Comma-separated, up to 8",
  "添加任务": "Add task",
  "返回当前对话": "Back to current conversation",
  "新对话": "New conversation",
  "对话列表": "Conversations",
  "查看对话列表": "View conversations",
  "对话设置": "Conversation settings",
  "暂停对话并返回草稿": "Pause conversation and return to the draft",
  "模型建议在你确认后才生效。切换页面会保留未发送输入。": "Model suggestions apply only after you confirm. Switching pages keeps unsent input.",
  "继续一段对话，或重新开始。": "Continue a conversation or start a new one.",
  "可继续的对话，可滚动": "Conversations available to continue; scrollable",
  "刷新列表": "Refresh list",
  "更多对话": "More conversations",
  "调整这段对话的方式和参考内容。建议仍需你确认后才生效。": "Adjust this conversation's mode and reference material. Suggestions still need your confirmation.",
  "帮助方式": "Help style",
  "先聊聊": "Talk first",
  "找一个小动作": "Find a small action",
  "一起安排": "Plan together",
  "保留方式": "Retention",
  "在本机保留": "Keep on this device",
  "改为仅本次会移除已保存的本机副本；当前内容只保留到退出应用。": "Switching to session-only removes the saved local copy. Current content lasts only until you quit the app.",
  "移除副本，改为仅本次": "Remove copy and use session-only",
  "继续保留": "Keep saved",
  "移除本机副本确认": "Confirm local copy removal",
  "保留期限": "Retention period",
  "保留天数": "Days to keep",
  "7 天": "7 days",
  "30 天": "30 days",
  "90 天": "90 days",
  "固定这段对话，不自动到期": "Pin this conversation with no automatic expiry",
  "本轮会参考什么": "What this turn will reference",
  "以下是本机预览，发送后才交给已配置的模型。": "This is a local preview. It reaches the configured model only when sent.",
  "加入今天已记录的专注摘要": "Include today's recorded focus summary",
  "加入有效的已确认安排偏好": "Include active, confirmed planning preferences",
  "未记录的时段是未知，不会当作休息或拖延。": "Unrecorded periods are unknown, not counted as rest or procrastination.",
  "逐项选择参考内容；不含用药、兴奋剂、自定义日常或日常发生记录。": "Choose reference items individually. Medication, stimulants, custom routines, and routine occurrence records are excluded.",
  "内容类别": "Content category",
  "收件原文": "Original inbox content",
  "普通日常排程": "Standard routine schedule",
  "已确认记忆": "Confirmed memories",
  "本机搜索": "Search this device",
  "搜索本机内容": "Search local content",
  "查看内容": "View content",
  "更多内容": "More content",
  "更新本轮预览": "Update this turn's preview",
  "管理这段对话": "Manage this conversation",
  "删除这段对话": "Delete this conversation",
  "删除这段对话、未发送输入和本机保存副本，无法从应用中撤销。已建立的任务与已独立确认的记忆会保留；记忆可在设置中另行管理。": "Deletes this conversation, unsent input, and the saved local copy. This cannot be undone in the app. Created tasks and independently confirmed memories remain; manage memories separately in settings.",
  "确认删除对话": "Confirm conversation deletion",
  "保留对话": "Keep conversation",
  "删除对话确认": "Confirm conversation deletion",
  "更早的记录": "Earlier records",
  "后面的记录": "Later records",
  "最新记录": "Latest records",
  "对话历史分页": "Conversation history pages",
  "对话与草稿版本，可分段查看完整历史": "Conversation and draft versions; browse the full history in sections",
  "已确认的修改与撤销": "Confirmed changes and reversals",
  "更多提交记录": "More change records",
  "变更前核对": "Review before applying",
  "输入消息": "Message input",
  "写点什么…": "Write something…",
  "暂停并返回": "Pause and return",
  "取消生成": "Cancel generation",
  "发送": "Send",
  "放进任务草稿": "Add to task draft",
  "返回时间线": "Back to timeline",
  "重新查看差异": "Review differences again",
  "确认以上修改": "Confirm these changes",
  "核对提交结果": "Check submission result",
  "取消这次变更": "Cancel this change",
  "刷新提交状态": "Refresh submission status",
  "核对后的变更操作": "Actions after reviewing changes",
  "这一段有实际推进": "I made progress in this session",
  "我停在 / 下次先做（可选）": "Where I stopped / what to do next (optional)",
  "例如：打开草稿，补上结论第一句": "For example: open the draft and add the first sentence of the conclusion",
  "下次从这里继续": "Pick up here next time",
  "到这里就好": "Stop here",
  "再做 8 分钟": "Another 8 minutes",
  "完整一轮": "A full session",
  "暂时跳过": "Skip for now",
  "保存落点": "Save handoff note",
  "编辑任务": "Edit task",
  "关闭编辑任务对话框": "Close task editor",
  "修改标题、备注和步骤；日期与其他属性可展开。": "Edit the title, notes, and steps. Expand dates and other details as needed.",
  "标题": "Title",
  "备注（可选）": "Notes (optional)",
  "安排日期": "Plan dates",
  "放在哪天": "Planned date",
  "截止": "Deadline",
  "有效期限": "Expiry",
  "其他属性": "Other details",
  "编辑能量": "Edit energy",
  "估时（分钟）": "Estimate (minutes)",
  "标签": "Tags",
  "修改范围": "Scope of changes",
  "未来频率": "Future frequency",
  "间隔周期": "Repeat interval",
  "推进方式": "Scheduling method",
  "未来重复星期": "Future repeat weekdays",
  "保存未来规则": "Save future rule",
  "暂停重复": "Pause recurrence",
  "恢复重复": "Resume recurrence",
  "结束重复": "End recurrence",
  "还有步骤没勾完": "Some steps are still unchecked",
  "取消完成任务": "Cancel task completion",
  "完成之后不能重新打开。确认现在就结束它吗？": "Completed tasks cannot be reopened. Complete this task now?",
  "先不完成": "Not yet",
  "就这样完成": "Complete as is",
  "今日回顾": "Today's review",
  "稍后继续回顾": "Continue review later",
  "这次略过": "Skip this time",
  "完成回顾": "Finish review",
  "升级啦！": "Level up",
  "又靠自己往前走了一步": "Another small step forward",
  "小步 - 快捷行动": "bubu - Quick actions",
  "小步 - 桌面伙伴": "bubu - Desktop companion",
  "宠物开发检验台": "Companion development tools",
  "关闭开发检验台": "Close development tools",
  "朝向": "Direction",
  "皮肤": "Skin",
  "等级": "Level",
  "显示全部": "Show all",
  "播放全部": "Play all",
  "能量曲线、宠物台词、喝水/站立提醒都按这个区间走；": "The energy curve, companion dialogue, and water/stretch reminders follow these hours.",
  "非工作时间不会唠叨，下班点会提醒收工。": "Reminders stay quiet outside work hours. A reminder marks the end of work.",
  "日常由桌宠提示；计时到点等使用系统通知": "The companion handles routine prompts; timer completion and similar events use system notifications.",
  "屏幕右下角像素角色浮现（60 秒后）": "A pixel character appears at the lower-right corner after 60 seconds.",
  "四角角色向中心聚集（再过 90 秒）": "Characters move inward from the four corners after another 90 seconds.",
  "半屏遮罩强提醒（再过 60 秒）": "A strong reminder covers half the screen after another 60 seconds.",
  "点角色可关闭；L2/L3 可按 ⌥⇧N 进入键盘操作，再用 Tab 选择、Esc 关闭。低刺激模式不会做四角聚拢，免打扰模式完全静默。": "Select a character to dismiss it. For L2/L3, press ⌥⇧N for keyboard control, Tab to choose, and Esc to close. Low-stimulation mode skips the corner convergence. Do not disturb stays completely silent.",
  "{label}数量未知": "{label}: count unknown",
  "{label} {count}": "{label} {count}",
  "待处理会话": "Pending conversations",
  "授权状态不可用": "Authorization status unavailable",
  "引用授权尚未就绪（{details}）": "Reference authorization is not ready ({details})",
  "引用授权已在本次运行中更新": "Reference authorization was updated for this run",
  "未保存会话": "Unsaved conversations",
  "保存结果未知的会话": "Conversations with an unknown save result",
  "本机会话保存未确认（{details}）": "Local conversation saving is unconfirmed ({details})",
  "资源释放": "Resource releases",
  "通知": "Notifications",
  "先前请求清理未确认（{details}）": "Cleanup of earlier requests is unconfirmed ({details})",
  "密钥状态暂不可确认": "Key status cannot be confirmed right now",
  "界面状态暂不可确认": "Interface state cannot be confirmed right now",
  "状态未知": "Status unknown",
  "已配置": "Configured",
  "未配置": "Not configured",
  "AI 已关闭": "AI is off",
  "尚未就绪 · 密钥状态未知": "Not ready · Key status unknown",
  "已就绪 · {model}": "Ready · {model}",
  "尚未就绪 · 请保存模型与密钥": "Not ready · Save a model and key",
  "状态暂不可确认": "Status cannot be confirmed right now",
  "请输入模型名称": "Enter a model name",
  "配置已保存，密钥未保存：系统安全存储不可用": "Configuration saved; key not saved: secure system storage is unavailable",
  "配置已保存 · 另有修改待保存": "Configuration saved · Other changes are unsaved",
  "配置与密钥已保存": "Configuration and key saved",
  "配置已保存": "Configuration saved",
  "已保存 · 下次 AI 请求生效": "Saved · Takes effect on the next AI request",
  "未保存 · 请检查模型名称与 HTTPS 地址": "Not saved · Check the model name and HTTPS address",
  "未导入 · 环境变量或安全存储不可用": "Not imported · Environment variable or secure storage unavailable",
  "未清除 · 系统安全存储不可用": "Not cleared · Secure system storage unavailable",
  "密钥已导入": "Key imported",
  "密钥已清除": "Key cleared",
  "密钥已导入 · 其他修改待保存": "Key imported · Other changes are unsaved",
  "密钥已清除 · 其他修改待保存": "Key cleared · Other changes are unsaved",
  "操作失败，请重试": "Action failed. Try again.",
  "修改待保存": "Unsaved changes",
  "已保存": "Saved",
  "开发运行不检查更新，安装正式版后可用": "Updates are unavailable in development mode. Install a release build to check for updates.",
  "此平台暂不支持应用内更新": "In-app updates are not supported on this platform yet",
  "这个安装包尚未配置更新源": "This build has no update source configured",
  "暂时无法检查更新，可以稍后重试": "Updates could not be checked. Try again later.",
  "下载未完成，可以重试，当前版本仍可使用": "Download incomplete. You can retry and keep using the current version.",
  "先结束当前专注或休息，再重启更新": "End the current focus or break session before restarting to update",
  "先处理本轮落点，再重启更新": "Finish this session’s wrap-up before restarting to update",
  "暂时无法确认数据已保存，请稍后重试": "Saved data cannot be confirmed right now. Try again later.",
  "暂时未能启动安装，请重试": "Installation could not start. Try again.",
  "下载已取消": "Download cancelled",
  "当前版本 {version}": "Current version {version}",
  "可检查是否有新版本": "Ready to check for updates",
  "正在检查…": "Checking…",
  "已是最新版本": "Up to date",
  "发现新版本 {version}": "Version {version} is available",
  "下载中 {percent}%": "Downloading {percent}%",
  "正在取消下载…": "Cancelling download…",
  "版本 {version} 已准备好": "Version {version} is ready",
  "正在重启更新…": "Restarting to update…",
  "更新暂不可用": "Updates are unavailable right now",
  "暂时无法读取更新状态": "Update status could not be read",
  "暂时无法完成，请稍后重试": "This could not be completed. Try again later.",
  "设置未保存，请重试": "Settings were not saved. Try again.",
  "暂时没有可以跟随的活动": "No activity to follow right now",
  "正在跟你听音乐": "Listening to music with you",
  "正在陪你写代码": "Keeping you company while you code",
  "正在陪你和 AI 对话": "Keeping you company while you chat with AI",
  "接收端口被占用，AI 工具的通知暂时收不到。": "The receiver port is in use. Notifications from AI tools are unavailable right now.",
  "AI 工具的通知暂时收不到。": "Notifications from AI tools are unavailable right now.",
  "还没有收到信号": "No signal received yet",
  "刚刚收到信号": "Signal received just now",
  "{minutes} 分钟前收到信号": "Signal received {minutes} minutes ago",
  "关闭时不读取任何应用信息。": "No app information is read while this is off.",
  "已复制": "Copied",
  "复制": "Copy",
  "设置没有保存，请重试。": "Settings were not saved. Try again.",
  "已完成步骤：{title}": "Completed step: {title}",
  "已跳过任务的只读步骤：{title}": "Read-only step of a skipped task: {title}",
  "已完成任务的只读步骤：{title}": "Read-only step of a completed task: {title}",
  "低能量": "Low energy",
  "中等能量": "Medium energy",
  "高能量": "High energy",
  "预约于 {time}": "Scheduled for {time}",
  "已失效": "Expired",
  "剩 {minutes} 分钟失效": "Expires in {minutes} minutes",
  "剩 {hours} 小时失效": "Expires in {hours} hours",
  "约 {minutes} 分钟": "About {minutes} minutes",
  "按标题自动推断": "Estimated from the title",
  "手动设定": "Set manually",
  "这一次已跳过": "This occurrence was skipped",
  "漏了 {count} 轮，今天可以重新开始": "Missed {count} occurrences. You can start again today.",
  "已专注 {time} · {count} 次": "Focused for {time} · {count} sessions",
  "已专注 {time}": "Focused for {time}",
  "帮我拆成几步": "Break into steps",
  "跳过这一次": "Skip this occurrence",
  "续期": "Extend expiry",
  "再做一遍": "Do again",
  "删除任务（可恢复）": "Delete task (recoverable)",
  "更多动作": "More actions",
  "更多动作：{title}": "More actions: {title}",
  "已完成的任务不再计时：{title}": "Completed tasks cannot be timed: {title}",
  "这一次已跳过：{title}": "This occurrence was skipped: {title}",
  "任务已失效，请先续期：{title}": "Task expired; extend its expiry first: {title}",
  "提前开始预约任务：{title}": "Start scheduled task early: {title}",
  "开始专注：{title}": "Start focus: {title}",
  "已完成任务：{title}": "Completed task: {title}",
  "已跳过任务，只读：{title}": "Skipped task, read-only: {title}",
  "完成任务：{title}": "Complete task: {title}",
  "← 正在专注": "← Focusing",
  "← 计时已暂停": "← Timer paused",
  "开始": "Start",
  "删除后会移到可恢复归档。继续吗？": "This task will move to the recoverable archive. Continue?",
  "加载中…": "Loading…",
  "归档目前是空的": "The archive is empty",
  "重复任务的某一次": "Recurring task occurrence",
  "一次性任务": "One-time task",
  "恢复任务：{title}": "Restore task: {title}",
  "恢复": "Restore",
  "条待整理": "notes to sort",
  "已清空": "All clear",
  "今天几点起？": "When did you wake up?",
  "点开自评": "Rate how you feel",
  "一次日常": "A routine",
  "你的自评": "Your self-rating",
  "专注负荷": "Focus load",
  "闪念判断": "Capture estimate",
  "闪念判断（{label}）": "Capture estimate ({label})",
  "闪念判断：{label}": "Capture estimate: {label}",
  "未知": "Unknown",
  "精力充沛": "Energized",
  "状态良好": "Feeling good",
  "中等": "Moderate",
  "有点累": "A little tired",
  "需要休息": "Rest needed",
  "↗ 正在回升": "↗ Rising",
  "↘ 正在下降": "↘ Falling",
  "→ 比较平稳": "→ Steady",
  "（估算）": "(estimated)",
  "（数据还少）": "(limited data)",
  "今天的能量曲线，现在约 {level}{trend}{confidence}": "Today's energy curve, about {level} now{trend}{confidence}",
  "吃药": "Medication",
  "咖啡因": "Caffeine",
  "正餐": "Meal",
  "加餐": "Snack",
  "活动": "Movement",
  "休息": "Rest",
  "会议": "Meeting",
  "自定义": "Custom",
  "第{index}次提醒的小时": "Hour for reminder {index}",
  "第{index}次提醒的分钟": "Minute for reminder {index}",
  "移除 {time}": "Remove {time}",
  "这条日常已经不在列表里了。": "This routine is no longer in the list.",
  "这一条对不上，重开一次面板再试。": "This occurrence does not match. Reopen the panel and try again.",
  "这条已经没有记录可以撤回了。": "This occurrence has no record left to undo.",
  "这条没有可撤回的记录。": "There is no record to undo for this occurrence.",
  "今天记的条数到上限了，先撤回几条。": "Today's record limit was reached. Undo some records first.",
  "这个状态不认识，什么都没记。": "This status is not recognized. Nothing was recorded.",
  "先给它起个名字。": "Enter a name first.",
  "这个种类不认识。": "This type is not recognized.",
  "日常的条数到上限了。": "The routine limit was reached.",
  "没有要改的东西。": "There are no changes to save.",
  "没记上，再试一次。": "That was not recorded. Try again.",
  "不提醒": "No reminders",
  "每周{days} {times}": "Every {days} at {times}",
  "随手": "Quick log",
  "做了": "Done",
  "跳过了": "Skipped",
  "没记上": "Not recorded",
  "今天没有提醒": "No reminders today",
  "还没有日常": "No routines yet",
  "撤回 {title}": "Undo {title}",
  "撤回": "Undo",
  "{title} 做了": "Mark {title} done",
  "{title} 跳过": "Skip {title}",
  "记一笔 {title}": "Log {title}",
  "已关闭": "Off",
  "提醒中": "Reminders on",
  "已静音": "Muted",
  "已启用": "Enabled",
  "已停用": "Disabled",
  "编辑 {title} 提醒": "Edit reminders for {title}",
  "{title} 提醒": "Reminders for {title}",
  "确认删除 {title}": "Confirm deletion of {title}",
  "删除 {title}": "Delete {title}",
  "真的删": "Confirm delete",
  "删除": "Delete",
  "添加日常后，在这里修改时间和提醒方式。": "After adding a routine, edit its times and reminders here.",
  "提醒已关": "Reminders off",
  "{count} 件到时间了": "{count} due now",
  "今天都记过了": "All logged today",
  "随手记一笔": "Log something",
  "选择一个提醒时间。": "Choose a reminder time.",
  "一条日常最多 {count} 个时间。": "A routine can have up to {count} reminder times.",
  "请选择有效的小时和分钟。": "Choose a valid hour and minute.",
  "每周至少选一天。": "Choose at least one day per week.",
  "给这个类型起个名字。": "Enter a name for this type.",
  "保存失败，请重试。": "Could not save. Try again.",
  "已添加": "Added",
  "提醒设置未保存，请重试。": "Reminder settings were not saved. Try again.",
  "再按一次就删掉，它今天的记录也会一起删。": "Press again to delete this routine and its records for today.",
  "保存日常": "Save routine",
  "昨天": "Yesterday",
  "{month}月{day}日": "{month}/{day}",
  "{when}的收口": "{when}: wrap-up",
  "{when}的启动": "{when}: getting started",
  "这里暂时没有内容。": "Nothing here yet.",
  "未命名": "Untitled",
  "待回顾 {count} 条": "{count} pending reviews",
  "打开": "Open",
  "就这样开始": "Start with these",
  "真实完成": "What you completed",
  "专注片段": "Focus sessions",
  "{minutes} 分钟（来自本地会话事实）": "{minutes} minutes (from local session records)",
  "留下的落点": "Where you left off",
  "仍在收件箱": "Still in your inbox",
  "昨日延续": "Carried over from yesterday",
  "今天先做这几件（勾掉不想做的；第一件会设为“现在”）": "Start with these today (uncheck any you do not want; the first becomes your Now task)",
  "今天新增": "Added today",
  "带自动失效": "With automatic expiry",
  "最近 7 天：专注 {time} · 完成 {done} 件 · 回来 {returns} 次": "Last 7 days: {time} focused · {done} completed · {returns} returns",
  "最近 12 周，每天一格；用方向键移动，回车查看当天": "Last 12 weeks, one cell per day. Use arrow keys to move and Enter to view a day.",
  "{day} · 专注 {time} · 完成 {count} 件": "{day} · {time} focused · {count} completed",
  "{day}，专注 {time}，完成 {count} 件，查看当天时间线": "{day}, {time} focused, {count} completed. View this day's timeline.",
  "{day} · 周{weekday}": "{day} · {weekday}",
  "关闭 {day} 的详情": "Close details for {day}",
  "专注": "Focus",
  "件完成": "completed",
  "次启动": "starts",
  "次返回": "returns",
  "统计和活动记录如何计算": "How statistics and activity records are counted",
  "启动：开始一轮专注或两分钟起步。返回：恢复已暂停的专注，或确认两分钟起步后的继续、收口。它们来自每日统计，不代表任务完成数。": "A start begins a focus session or a two-minute start. A return resumes paused focus or confirms continuing or wrapping up after two minutes. These daily statistics are separate from completed task counts.",
  "日常等具体活动记录在下方时间线中。统计为零，不代表没有行动。": "Routine and other activity records appear in the timeline below. Zero statistics do not mean no action was taken.",
  "正在删除": "Deleting",
  "来源暂不可用，这次未删除": "Source unavailable; nothing deleted",
  "来源清理尚未完成": "Source cleanup is incomplete",
  "删除结果尚待核对": "Deletion result needs checking",
  "这条记录与来源已不在应用记录中": "This record and its source are no longer in the app",
  "记录与来源已删除": "Record and source deleted",
  "继续清理": "Continue cleanup",
  "重试核对": "Check again",
  "确定删除？": "Confirm delete?",
  "正在读取变更": "Loading changes",
  "暂时无法读取，重试": "Could not load. Retry",
  "变更详情": "Change details",
  "暂时无法读取活动记录": "Activity records could not be loaded",
  "活动类型": "Activity type",
  "全部": "All",
  "收件": "Inbox",
  "AI 变更": "AI changes",
  "{count} 条活动 · 专注 {time}": "{count} activities · {time} focused",
  "记录覆盖仅代表已保存的活动": "Coverage includes only saved activities",
  "深夜": "Night",
  "上午": "Morning",
  "下午": "Afternoon",
  "晚上": "Evening",
  "不在当前列表里的任务": "Task no longer in the current list",
  "内容已移除": "Content removed",
  "记录": "Recorded",
  "私密记录": "Private record",
  "1 条便签": "1 note",
  "收下": "Captured",
  "1 条收件": "1 inbox item",
  "已处理": "Processed",
  "已修改": "Updated",
  "日常计划": "Routine schedule",
  "已移除的日常": "Removed routine",
  "提醒": "Reminder",
  "提醒时段结束": "Reminder window ended",
  "两分钟启动": "Two-minute start",
  "专注结束": "Focus ended",
  "完成": "Completed",
  "你确认的估计试用": "Your confirmed estimate trial",
  "已调整": "Adjusted",
  "按你的自评更新了能量模型": "Energy model updated from your self-ratings",
  "记录类型暂不可用": "Record type unavailable",
  "其他记录": "Other record",
  "其他": "Other",
  "较早日期的能量打卡未完整保留，不画失真的曲线": "Earlier energy ratings are incomplete, so no potentially misleading curve is shown",
  "夏令时切换日的能量采样无法准确覆盖当天，不画失真的曲线": "Energy samples cannot fully represent this daylight-saving transition day, so no curve is shown",
  "估计能量曲线未启用或不可用": "The estimated energy curve is off or unavailable",
  "这天没有足够的能量记录": "Not enough energy records for this day",
  "估计能量 {low}–{high}（10–90，仅为估计）": "Estimated energy {low}–{high} (10–90, estimate only)",
  "能量估计": "Energy estimate",
  " · 当时估计能量约 {level}": " · Estimated energy then: about {level}",
  "{time} · 你留下的情绪记录 · {text}": "{time} · Your mood note · {text}",
  "心情": "Mood",
  "删除这条情绪记录": "Delete this mood note",
  "{seconds}秒": "{seconds}s",
  "刚开始": "Just started",
  "{hours} 小时{minutes}": "{hours} hours{minutes}",
  " {minutes} 分": " {minutes} min",
  "{time}没有记录": "No records for {time}",
  "暂无活动记录。没有逐条记录，不代表没有行动。": "No activity records. Missing records do not mean no action was taken.",
  "{count} 项操作": "{count} operations",
  "已确认撤销": "Confirmed undo",
  "已确认修改": "Confirmed changes",
  "任务调整": "Task changes",
  "收件已处理": "Inbox item processed",
  "日常计划调整": "Routine schedule changes",
  "来源：经本人确认的 AI 协作": "Source: AI collaboration confirmed by you",
  "状态：已提交": "Status: committed",
  "变更": "Change",
  "{label}：{items}": "{label}: {items}",
  "回执：{receipt}": "Receipt: {receipt}",
  "发生时区：{timezone} (UTC{offset})": "Event time zone: {timezone} (UTC{offset})",
  "补录时间：{time}": "Recorded later at: {time}",
  "预览已到期，重新查看后可以确认。": "This preview has expired. Review it again before confirming.",
  "本次打开的预览较多，稍后可以再试。已有内容未改变。": "Several previews are open. Try again shortly. Existing content is unchanged.",
  "安排偏好已经变化，请重新核对。": "Planning preferences have changed. Please review them again.",
  "已有 24 条偏好，可以选择已有条目修改。": "You already have 24 preferences. Choose an existing one to edit.",
  "本机偏好变更记录已达到 512 条，本次未保存；仍可以撤销最近一次变更。": "The local history has reached 512 preference changes. This change was not saved; you can still undo the most recent change.",
  "时间段和偏好需要填写完整；结束时间应晚于开始时间。": "Complete the time range and preference. The end time must be after the start.",
  "这份建议的来源已经变化或停止引用，需要回到对话重新核对。": "The source for this suggestion has changed or is no longer referenced. Return to the conversation to review it.",
  "这份建议已经保存，可以在已有偏好中查看和修改。": "This suggestion has already been saved. You can view and edit it in existing preferences.",
  "这份对话建议暂时不可用。已有偏好未改变。": "This conversation suggestion is unavailable. Existing preferences are unchanged.",
  "修改后的目标与原建议不一致，请重新打开原建议。": "The edited target does not match the original suggestion. Reopen the original suggestion.",
  "自评记录范围已经变化，请重新核对。": "The self-check recording scope has changed. Please review it again.",
  "开启本机记录并积累足够自评后，才可以试用曲线。": "Enable local recording and collect enough self-checks before trying a curve adjustment.",
  "自评记录的数量或时间覆盖还不足。": "There are not enough self-checks or enough time coverage yet.",
  "已有一项试用，结束后才能开始另一项。": "A trial is already active. End it before starting another.",
  "曲线参数已经变化，请重新比较。": "The curve parameters have changed. Compare them again.",
  "曲线依据已经变化，请重新比较。": "The data behind the curve has changed. Compare it again.",
  "试用值超出本次可编辑范围。": "The trial value is outside the editable range for this preview.",
  "参数、试用值或期限不完整。": "The parameter, trial value, or duration is incomplete.",
  "这次偏好变更已不能撤销。": "This preference change can no longer be undone.",
  "这项试用已结束或不能撤销。": "This trial has ended or can no longer be undone.",
  "重试核对这次保存": "Recheck this save",
  "确认请求正在处理，结果尚未核对。": "The confirmation request is processing. Its outcome has not been verified.",
  "保存结果暂时无法确认。重新读取或重试会核对同一次请求，不会创建另一项变更。": "The save outcome is unconfirmed. Reloading or retrying checks the same request without creating another change.",
  "预览已隐藏，但取消结果尚未确认。重新读取后可以核对。": "The preview is hidden, but cancellation is unconfirmed. Reload to check.",
  "已核对上次确认的本机变更。": "The previous local change has been verified.",
  "已读取本机设置。变更会先显示预览。": "Local settings loaded. Changes will be previewed first.",
  "保存结果仍待核对，确认请求的标识已保留。": "The save outcome still needs checking. The confirmation request identity is retained.",
  "暂时无法读取本机设置，已有内容未改变。": "Local settings could not be read. Existing content is unchanged.",
  "这份对话建议暂时不能核对，已有偏好未改变。": "This conversation suggestion cannot be reviewed right now. Existing preferences are unchanged.",
  "返回的预览与这份对话建议不一致，请重新打开。": "The returned preview does not match this conversation suggestion. Reopen it.",
  "对话建议已带入，可以修改时间段、难度和期限。确认后才保存。": "The conversation suggestion is ready. You can edit the time range, difficulty, and duration. It is saved only after confirmation.",
  "对话建议读取未完成，已有偏好未改变。": "The conversation suggestion could not be read. Existing preferences are unchanged.",
  "当前还不能开始新的曲线试用。": "A new curve trial cannot be started right now.",
  "表单已改变，请重新查看变更。": "The form has changed. Review the changes again.",
  "暂时无法准备预览，已有内容未改变。": "A preview could not be prepared. Existing content is unchanged.",
  "返回的预览与当前选择不一致，请重新读取。": "The returned preview does not match the current selection. Reload it.",
  "预览已准备好，尚未保存。": "The preview is ready. Nothing has been saved yet.",
  "预览未成功，已有内容未改变。": "The preview failed. Existing content is unchanged.",
  "曲线试用已开始，到期后恢复原参数。": "The curve trial has started. The original parameters return when it expires.",
  "本机自评记录范围已更新。": "The local self-check recording scope has been updated.",
  "安排偏好已保存，自评保持原样。": "Planning preference saved. Self-checks are unchanged.",
  "这次请求的结果仍无法确认；原标识已保留，请重新读取并核对当前记录。": "The outcome of this request is still unconfirmed. Its identity is retained; reload and check the current record.",
  "尚未确认保存，请重新核对。": "Saving has not been confirmed. Please check again.",
  "当前没有可撤销的变更。": "There is no change available to undo.",
  "试用已结束，保留已发生的自评。": "The trial has ended. Existing self-checks are retained.",
  "上次偏好变更已撤销。": "The last preference change has been undone.",
  "无法撤销，请重新读取后核对。": "The change could not be undone. Reload to check.",
  "撤销结果暂时无法确认，请重新读取。": "The undo outcome is unconfirmed. Reload to check.",
  "预览已关闭。": "Preview closed.",
  "不设到期": "No expiry",
  " · 已到期": " · Expired",
  "已保存 {count}/24 条偏好": "{count}/24 preferences saved",
  "暂无安排偏好": "No planning preferences yet",
  " · 变更记录已满，暂不能保存新修改": " · Change history is full; new edits cannot be saved",
  "本机保留 {retained} 条。近 30 天：{samples} 条有效自评，{days} 个日期，跨度 {elapsed} 天。": "{retained} retained locally. Last 30 days: {samples} valid self-checks across {days} dates, spanning {elapsed} days.",
  "其中 {count} 条没有当时的估计，不能据此推算偏差。": "{count} have no estimate from that time, so they cannot be used to calculate a difference.",
  "正在试用：{parameter} {from} → {to} 分钟；{expiry} 到期。": "Trial active: {parameter} {from} → {to} min; expires {expiry}.",
  "试用目前未应用：{reason}。可以恢复或重新核对。": "Trial is not currently applied: {reason}. You can restore it or review it again.",
  "已到期": "Expired",
  "依据或参数已变化": "Data or parameters have changed",
  "可以比较曲线并试用，效果尚待观察。": "You can compare curves and start a trial. Its effect is still unknown.",
  "开启自评记录后可积累试用所需的样本。": "Enable self-check recording to collect the samples needed for a trial.",
  "现有自评覆盖不足，暂不提供曲线试用。": "Self-check coverage is insufficient for a curve trial yet.",
  "当前参数暂不可用。": "The current parameter is unavailable.",
  "当前 {current} 分钟 · 可选 {min}–{max} 分钟": "Current: {current} min · Available: {min}–{max} min",
  "自评记录范围": "Self-check recording scope",
  "曲线试用预览": "Curve trial preview",
  "安排偏好预览": "Planning preference preview",
  "来源：对话中的安排建议；本次只保存安排偏好。": "Source: a planning suggestion from the conversation. Only the planning preference will be saved.",
  "原来：{preference}": "Before: {preference}",
  "新增一条偏好": "Add a preference",
  "确认后：{preference}\n有效至：{expiry}\n自评和个人观测保持原样。": "After confirmation: {preference}\nValid until: {expiry}\nSelf-checks and personal observations stay unchanged.",
  "新的自评记录：{enabled}\n清除已有历史：{count} 条{effect}\n不补写历史，不清除当前最近一次自评。": "New self-check records: {enabled}\nDelete existing history: {count} records{effect}\nNo historical backfill; your most recent self-check is not deleted.",
  "开启，仅本机": "On, local only",
  "，确认后不可撤销": "; cannot be undone after confirmation",
  "，继续保留": "; keep existing records",
  "{parameter}：{from} → {to} 分钟\n自评依据：{samples} 条，{days} 个日期\n确认时开始，{expiry} 到期；可以随时结束试用。\n样本覆盖不证明调整有效，也不能说明身体状况。": "{parameter}: {from} → {to} min\nSelf-check evidence: {samples} records across {days} dates\nStarts on confirmation and expires {expiry}; you can end the trial at any time.\nSample coverage does not prove the adjustment works or indicate a medical condition.",
  "此预览可确认至 {expiry}；修改表单后需要重新预览。": "This preview can be confirmed until {expiry}. Editing the form requires a new preview.",
  "实线：当前估计　虚线：建议估计": "Solid: current estimate    Dashed: suggested estimate",
  "当前与建议的非医学能量估计曲线": "Current and suggested non-medical energy estimate curves",
  "确认记录范围": "Confirm recording scope",
  "确认开始试用": "Confirm start of trial",
  "确认保存偏好": "Confirm save preference",
  "内容已在别处修改；本次未应用。需要重新查看最新差异。": "The content was edited elsewhere. Nothing was applied. Review the latest differences.",
  "这份差异版本已失效；本次未应用，需要重新预览。": "This version of the differences is no longer valid. Nothing was applied. Preview again.",
  "实际差异已经变化；本次未应用，需要重新预览。": "The actual differences have changed. Nothing was applied. Preview again.",
  "确认时间已过期；建议仍在，需要重新预览。": "The confirmation has expired. The suggestion remains; preview it again.",
  "参考范围或模型配置已变化；需要重新核对参考范围。": "The reference scope or model settings changed. Review the reference scope again.",
  "建议依据的记录已变化；需要在最新参考范围内继续对话，再生成建议。": "Records behind this suggestion changed. Continue the conversation with the latest reference scope, then generate a new suggestion.",
  "这次预览已失效；需要重新核对差异。": "This preview is no longer valid. Review the differences again.",
  "这次预览已失效；原建议仍在，可以重新核对差异。": "This preview is no longer valid. The original suggestion remains; review its differences again.",
  "这次修改当前不能撤销；可能已有后续修改或超过保留期限。": "This change cannot be undone now. There may be later edits, or its retention period may have ended.",
  "这项操作已有提交记录，请核对回执。": "This operation already has a commit record. Check the receipt.",
  "编辑内容未通过校验；尚未应用，可以继续修改。": "The edits did not pass validation. Nothing was applied; you can keep editing.",
  "所选内容没有实际变化，未提交。": "The selected content has no actual changes. Nothing was submitted.",
  "本机提交记录暂时无法保存；未应用，建议仍在。": "The local commit record could not be saved. Nothing was applied; the suggestion remains.",
  "参考范围或对话已变化，需要重新查看差异。": "The reference scope or conversation changed. Review the differences again.",
  "本机差异暂不可用；没有应用任何建议。": "Local differences are unavailable. No suggestions were applied.",
  "下列是重新核对后的撤销差异，确认后才提交。": "These are the refreshed undo differences. They will be submitted only after confirmation.",
  "这些修改尚未提交。逐项核对后可以确认，也可以继续留在草稿里。": "These changes have not been submitted. Review each one before confirming, or leave them in the draft.",
  "至少保留一项可应用操作。": "Keep at least one operation that can be applied.",
  "差异读取未完成；没有提交，可以重试预览。": "The differences could not be read. Nothing was submitted; you can retry the preview.",
  "所选操作已变化，重新查看差异后才能确认。": "The selected operations changed. Review the differences again before confirming.",
  "内容已编辑，重新查看差异后才能确认。": "The content was edited. Review the differences again before confirming.",
  "变更已落入本机状态，但持久保存尚未确认。核对保存结果前不可撤销或重新应用。": "The change is in local state, but durable saving is unconfirmed. Do not undo or reapply it until the save is checked.",
  "撤销已提交，原修改和撤销回执都保留在历史中。": "Undo submitted. Both the original change and its undo receipt remain in history.",
  "已收到本机提交回执。": "Local commit receipt received.",
  "正在核对同一次确认的提交记录…": "Checking the commit record for the same confirmation…",
  "正在提交已核对的变更…": "Submitting the reviewed changes…",
  "提交结果暂时无法核验，不能判断是否已应用。仅核对同一次确认，不重新执行建议。": "The outcome cannot be verified, so it is unknown whether this was applied. Only the same confirmation will be checked; the suggestion will not run again.",
  "变更已落入本机状态，但持久保存尚未确认。核对同一次确认的保存结果，不会重新应用建议。": "The change is in local state, but durable saving is unconfirmed. Checking the same confirmation will not reapply the suggestion.",
  "本次未应用，建议仍在。可以核对最新差异后再试。": "Nothing was applied. The suggestion remains; review the latest differences before retrying.",
  "尚未确认提交结果；核对同一次确认的回执后再继续。": "The outcome is unconfirmed. Check the receipt for the same confirmation before continuing.",
  "提交结果尚未确认；核对回执会沿用同一次确认，不重复建立任务。": "The outcome is unconfirmed. Receipt checking uses the same confirmation and will not create duplicate tasks.",
  "回执当前不可用；无法确认更多提交详情。": "The receipt is unavailable. Further commit details cannot be confirmed.",
  "先前的撤销提交结果尚未确认；可以核对同一次确认的回执。": "The previous undo outcome is unconfirmed. You can check the receipt for that same confirmation.",
  "回执读取未完成；已有提交状态未改变。": "The receipt could not be read. The existing commit status is unchanged.",
  "撤销差异暂不可用，没有撤销任何修改。": "Undo differences are unavailable. No changes were undone.",
  "撤销差异读取未完成；原修改未变。": "Undo differences could not be read. The original change is unchanged.",
  "这次待确认变更已取消；原建议仍在对话中。": "This pending change was cancelled. The original suggestion remains in the conversation.",
  "取消未确认；当前确认入口已失效。": "Cancellation is unconfirmed. The current confirmation is no longer valid.",
  "先前的提交结果尚未确认；仅核对同一次确认，不重新执行建议。": "The previous outcome is unconfirmed. Only the same confirmation will be checked; the suggestion will not run again.",
  "本机变更待确认持久保存": "Local change awaiting durable-save confirmation",
  "已提交撤销": "Undo submitted",
  "修改已撤销": "Change undone",
  "回执 {receipt} · 版本 {version}": "Receipt {receipt} · Version {version}",
  "提交历史暂不可用；不能据此判断没有提交记录。": "Commit history is unavailable. This does not mean there are no commit records.",
  "修改任务": "Edit task",
  "收件转任务": "Convert inbox item to task",
  "收件留存": "Keep inbox item",
  "撤销任务修改": "Undo task changes",
  "撤销日常排程": "Undo routine schedule",
  "计划日": "Planned date",
  "任务能量": "Task energy",
  "自动能量": "Automatic energy",
  "建议时长": "Suggested duration",
  "估时来源": "Estimate source",
  "后续任务步骤": "Following task steps",
  "分类": "Classification",
  "去向": "Destination",
  "相关能量信号": "Related energy signals",
  "提醒排程": "Reminder schedule",
  "新建任务不支持从此处撤销": "Task creation cannot be undone here",
  "收件处理不支持从此处撤销": "Inbox processing cannot be undone here",
  "没有变化": "No changes",
  "撤销操作不提供再次撤销": "An undo cannot itself be undone",
  "无": "None",
  "随此操作一起变化": "Changes along with this operation",
  "原来": "Before",
  "变为": "After",
  "撤销前会重新核对当前版本": "The current version will be checked again before undoing",
  "此项不提供撤销": "Undo is unavailable for this item",
  "修改的保存状态待核对": "Save status needs checking",
  "这次修改已撤销": "This change was undone",
  "已确认的修改": "Confirmed changes",
  "撤销前核对": "Review before undoing",
  "回执 {receipt} · 提交版本 {revision}": "Receipt {receipt} · Committed version {revision}",
  "变更已落入本机状态；持久保存尚未确认，时间线记录待同步。": "The change is in local state. Durable saving is unconfirmed and the timeline record is awaiting sync.",
  "修改已提交，时间线记录待同步。重试同步不会再次执行修改。": "Changes committed. The timeline record is awaiting sync. Retrying sync will not apply the changes again.",
  "修改已提交，时间线记录已同步。": "Changes committed and timeline record synced.",
  "修改已提交，时间线同步状态尚未确认。": "Changes committed. Timeline sync is unconfirmed.",
  "详细内容已到期或移除，保留提交记录。": "Details have expired or been removed. The commit record remains.",
  "这次修改目前无法撤销。": "This change cannot currently be undone.",
  "{status} · 版本 {version}": "{status} · Version {version}",
  "提交结果待核对": "Outcome needs checking",
  "建议原因：{reason}": "Reason for suggestion: {reason}",
  "来源：{sources}": "Sources: {sources}",
  "未提供额外来源": "No additional sources provided",
  "时区：{timezone}。仅调整将来提醒，不改变已发生记录。": "Time zone: {timezone}. Only future reminders change; existing records stay unchanged.",
  "确认这次撤销": "Confirm this undo",
  "核对保存结果": "Check save outcome",
  "标签（逗号分隔）": "Tags (comma-separated)",
  "改写步骤": "Rename step",
  "新增步骤": "Add step",
  "重复任务作用范围": "Repeating task scope",
  "留存分类": "Keep as",
  "未分类": "Unclassified",
  "要做的事": "To do",
  "想法": "Idea",
  "重复范围": "Repeat on",
  "所选星期": "Selected weekdays",
  "提醒时间（HH:MM，逗号分隔）": "Reminder times (HH:MM, comma-separated)",
  "星期（1–7，逗号分隔；仅所选星期时使用）": "Weekdays (1–7, comma-separated; only for selected weekdays)",
  "提醒时间窗口（分钟）": "Reminder window (minutes)",
  "编辑这项建议": "Edit this suggestion",
  "编辑后需要重新查看差异，旧确认失效。": "After editing, preview the differences again. The previous confirmation is invalid.",
  "这份建议已经存入记忆，可以在列表中查看、修改或恢复原条目。": "This suggestion is already saved as a memory. You can view, edit, or restore the original item in the list.",
  "这份建议引用的来源太多，可以在对话中缩小范围后重新提出。": "This suggestion cites too many sources. Narrow the scope in the conversation and propose it again.",
  "这条记忆已经变化。未应用本次修改，刷新后重新核对。": "This memory has changed. Your change was not applied. Refresh and review it again.",
  "这次确认已失效，内容仍在，需要重新查看差异。": "This confirmation is no longer valid. The content remains; review the differences again.",
  "确认时间已过期，内容仍在，需要重新查看差异。": "The confirmation has expired. The content remains; review the differences again.",
  "影响范围已经变化，未应用本次修改，需要重新核对。": "The affected scope has changed. Nothing was applied; review it again.",
  "已有同主题和范围的记忆。可以选择现有条目修改，保持它的身份。": "A memory with this subject and scope already exists. Edit the existing item to keep its identity.",
  "这条内容的来源已被永久移除，不能重新加入。": "The source of this content was permanently removed. It cannot be added again.",
  "本机记忆库暂不可用；未确认任何修改。": "The local memory store is unavailable. No changes have been confirmed.",
  "这次修改已超过撤销期限，或有了后续修改；没有撤销。": "This change is past its undo deadline or has later edits. Nothing was undone.",
  "记忆变更记录容量已满，已有记录会保留；本次没有新增修改。": "Memory change history is full. Existing records remain; no new changes were added.",
  "记忆容量已满。现有内容仍在，可以先整理不再需要的条目。": "Memory capacity is full. Existing content remains; you can organize items you no longer need.",
  "核对遗忘清理结果": "Check forgetting cleanup",
  "本机记忆列表暂不可用；已有内容与状态尚未确认。": "The local memory list is unavailable. Existing content and status are unconfirmed.",
  "本机记忆列表读取未完成，不能据此判断没有内容。": "The local memory list could not be read. This does not mean it is empty.",
  "这条记忆不在当前已读取内容中，请先打开对应状态再核对。": "This memory is not in the loaded items. Open its status tab to review it first.",
  "修改这条记忆": "Edit this memory",
  "保持 ID {id} · 当前版本 {version}": "Keep ID {id} · Current version {version}",
  "先查看差异，确认后才保存": "Preview differences first; save only after confirmation",
  "差异已准备好，尚未保存。": "The differences are ready. Nothing has been saved yet.",
  "未能准备记忆差异；内容仍在，没有确认修改。": "Memory differences could not be prepared. The content remains; no changes were confirmed.",
  "选择现有条目后，会保留当前输入并重新核对替换差异。": "Choose an existing item to keep your current input and review the replacement differences.",
  "核对替换 {subject}": "Review replacement: {subject}",
  "差异读取未完成；内容仍在，可以重试。": "The differences could not be read. The content remains; you can retry.",
  "现有条目尚未完整读取，当前输入仍在；可以刷新后再核对。": "The existing item has not been fully loaded. Your input remains; refresh to review it.",
  "这条对话建议暂时不能作为记忆核对；没有保存。": "This conversation suggestion cannot be reviewed as a memory right now. Nothing was saved.",
  "核对这条记忆的修改": "Review changes to this memory",
  "核对并修改这条对话建议": "Review and edit this conversation suggestion",
  "保持 ID {id} · 当前版本 {version}。": "Keep ID {id} · Current version {version}.",
  "来源仍关联原对话建议；修改后需要重新查看差异，确认前不会保存记忆。": "The source remains linked to the original conversation suggestion. Preview differences again after editing; no memory is saved before confirmation.",
  "对话记忆建议读取未完成，没有保存。": "The conversation memory suggestion could not be read. Nothing was saved.",
  "主题和内容需要完整填写，分别最多 200 字和 500 字；原文仍在。": "Complete the subject and content, up to 200 and 500 characters respectively. Your text is retained.",
  "回收期限已过，永久清理待完成；这条记忆不能再恢复使用。": "The recycle period has ended and permanent cleanup is pending. This memory cannot be restored.",
  "记忆修改已提交，相关上下文失效处理尚待完成；暂不能继续修改。": "The memory change is committed. Related context invalidation is pending; further changes are paused.",
  "提交结果尚未确认；保留这次确认，核对原结果后再继续。": "The outcome is unconfirmed. This confirmation is retained; check its original outcome before continuing.",
  "永久遗忘已生效，相关正文清理仍待完成；这不是可以重新执行的普通失败。": "Permanent forgetting has taken effect. Related content cleanup is pending; this is not an ordinary failure that can be rerun.",
  "本次修改未确认保存；内容仍在，可以重新核对。": "Saving this change is unconfirmed. The content remains; you can check again.",
  "提交结果尚未确认；核对同一次确认的结果后再继续。": "The outcome is unconfirmed. Check the same confirmation before continuing.",
  "遗忘已生效，正文清理仍未确认完成；后续修改继续暂停。": "Forgetting has taken effect, but content cleanup is not yet confirmed. Further changes remain paused.",
  "回执读取未完成，已有提交状态没有改变。": "The receipt could not be read. The existing commit status is unchanged.",
  "回执读取未完成；待处理状态保持不变。": "The receipt could not be read. The pending status is unchanged.",
  "撤销差异读取未完成；原修改仍在。": "Undo differences could not be read. The original change remains.",
  "内容已修改；重新查看差异后才能确认保存。": "The content changed. Review the differences again before confirming the save.",
  "本人陈述": "Your statement",
  "本人编辑或确认": "Your edit or confirmation",
  "由记录汇总": "Summarized from records",
  "模型建议，尚未确认": "Model suggestion, not yet confirmed",
  "旧版导入，确认记录未知": "Legacy import, confirmation unknown",
  "新增记忆": "Add memory",
  "修改记忆": "Edit memory",
  "确认并启用": "Confirm and enable",
  "移到回收区": "Move to recycle area",
  "恢复为暂停使用": "Restore as paused",
  "永久移除": "Remove permanently",
  "撤销记忆修改": "Undo memory change",
  "主题": "Subject",
  "状态": "Status",
  "开始生效": "Effective from",
  "有效至": "Valid until",
  "回收保留至": "Recycle until",
  "来源": "Source",
  "本人确认时间": "Your confirmation time",
  "来源未知": "Unknown source",
  "普通": "Standard",
  "查看恢复差异": "Preview restore differences",
  "永久移除…": "Remove permanently…",
  "核对并确认": "Review and confirm",
  "恢复使用": "Resume use",
  "未知类别": "Unknown category",
  "保留期已到，等待完成清理": "Retention ended; cleanup pending",
  "范围未知": "Unknown scope",
  "仅本机": "Local only",
  "有效至：{expiry}": "Valid until: {expiry}",
  "来源与使用记录": "Sources and usage",
  "版本 {version}": "Version {version}",
  "最近使用：{used} · 有效至：{expiry}": "Last used: {used} · Valid until: {expiry}",
  "尚无使用记录": "No usage recorded",
  "来源引用：{sources}": "Source references: {sources}",
  "未提供": "Not provided",
  "与 {ids} 有冲突，暂不用于模型上下文。": "Conflicts with {ids}; excluded from model context for now.",
  "当前不用于对话。": "Not currently used in conversations.",
  "已停止使用，正文仍留在本机回收区。": "No longer used. The content remains in the local recycle area.",
  "回收保留至 {expiry}（30 天）；{effect}": "Retained until {expiry} (30 days); {effect}",
  "期限已过，永久清理待完成，不能再恢复。涉及其他关联记忆时，需要另行核对扩大后的永久移除范围。": "The deadline has passed. Permanent cleanup is pending and this cannot be restored. If other memories are linked, the expanded removal scope must be reviewed separately.",
  "到期后自动永久清理本条；涉及其他关联记忆时，扩大范围需另行确认。": "This item is permanently cleaned up after expiry. If other memories are linked, the expanded scope needs separate confirmation.",
  "回收期限尚未确认；永久移除另行核对。": "The recycle deadline is unconfirmed. Permanent removal requires separate review.",
  "暂不可用": "Unavailable",
  "{count} 条{more}": "{count} items{more}",
  " · 还有更多": " · More available",
  "本机记忆库暂不可用；不能据此判断没有记忆。": "The local memory store is unavailable. This does not mean there are no memories.",
  "展开这一组时读取本机记录。": "Local records load when this group is expanded.",
  "暂无{status}的记忆。": "No memories with status: {status}.",
  "目标：{id} · {version}": "Target: {id} · {version}",
  "新增": "New",
  "尚未提交；只有核对后的确认会保存。": "Not submitted. Only confirmation after review saves the change.",
  "无此记忆": "No such memory",
  "移除": "Remove",
  "影响的记忆：{ids}": "Affected memories: {ids}",
  "未提供；不推断来源": "Not provided; no source is inferred",
  "停止用于上下文的来源：{sources}": "Sources no longer used in context: {sources}",
  "回收区保留 30 天，至 {expiry}。到期后将自动永久清理本条及其旧版本，无法撤销；若同一来源关联其他记忆或派生内容，将暂停清理并另行核对扩大后的范围。已发送给外部模型服务商的副本不在清理范围内。": "Retained in the recycle area for 30 days, until {expiry}. This item and its old versions are then permanently deleted and cannot be restored. If the source links to other memories or derived content, cleanup pauses for separate review of the expanded scope. Copies already sent to external model providers are not included.",
  "期限尚未确认": "Deadline unconfirmed",
  "可申请撤销至 {expiry}；撤销前仍会核对版本。": "Undo may be requested until {expiry}; the version is still checked before undoing.",
  "此操作不提供撤销。": "This operation cannot be undone.",
  "确认永久移除这些内容": "Confirm permanent removal of this content",
  "确认以上变更": "Confirm these changes",
  "已收到本机提交回执 {receipt} · {operation} · {status}": "Local commit receipt {receipt} · {operation} · {status}",
  "记忆修改": "Memory change",
  "时间线记录待同步": "Timeline record awaiting sync",
  "时间线已同步": "Timeline synced",
  "时间线同步状态未知": "Timeline sync unknown",
  "改写步骤 {index}": "Rename step {index}",
  "新增步骤 {index}": "Add step {index}",
  "关闭记录": "Off",
  "暂停这条记忆": "Pause this memory",
  "逾期 {days} 天": "{days} days overdue",
  "已逾期": "Overdue",
  "今天 DDL": "Due today",
  "明天 DDL": "Due tomorrow",
  "{days} 天后": "In {days} days",
  "今天 {time}": "Today {time}",
  "明天 {time}": "Tomorrow {time}",
  "昨天 {time}": "Yesterday {time}",
  "每周重复需要至少选一个星期；当前输入不会丢。": "Select at least one weekday for weekly repetition. Your input is retained.",
  "→ {time} 失效": "→ Expires {time}",
  "→ 不会自动失效": "→ Does not expire automatically",
  "可开始时间无效，当前输入不会保存。": "The start-available time is invalid. The current input will not be saved.",
  "每个标签最多 {count} 个字符；输入仍然保留。": "Each tag can have up to {count} characters. Your input is retained.",
  "每个任务最多 {count} 个标签；输入仍然保留。": "Each task can have up to {count} tags. Your input is retained.",
  "估时必须是 {min}–{max} 的整数分钟；输入仍然保留。": "The estimate must be a whole number from {min} to {max} minutes. Your input is retained.",
  "重复间隔必须是 {range} 的整数；当前输入不会丢。": "The repeat interval must be a whole number in {range}. Your input is retained.",
  "重复间隔必须是 {range} 的整数。": "The repeat interval must be a whole number in {range}.",
  "两分钟到了，已经启动成功": "Two minutes done. You got started.",
  "收工前，给下次留个入口": "Before you finish, leave a place to pick up",
  "给下一次留个入口": "Leave a place to pick up next time",
  "不用证明什么。选择此刻最适合你的落点：": "Nothing to prove. Choose what works for you now:",
  "这不是一次完成结算。留一句下次能直接动手的提示，或安心跳过。": "This does not mark the task complete. Leave a small next step, or skip it for now.",
  "休息正在进行。你可以留一句落点，也可以跳过，之后再决定。": "Your break is running. Leave a note for next time, or skip it and decide later.",
  "休息已经暂停。上一轮落点仍保留，准备好时再处理。": "Your break is paused. The previous session's next-step prompt is saved for when you are ready.",
  "这段专注的落点仍为你保留，可以留一句下次入口，也可以跳过。": "This session's next-step prompt is still here. Leave a note for next time, or skip it.",
  "写下一句可以直接开始的动作，或者选择“暂时跳过”。": "Write a concrete next step, or choose “Skip for now”.",
  "这次结果尚未确认，当前决定仍保留，请重试。": "The outcome is unconfirmed. Your current choice is retained; please retry.",
  "{minutes}分": "{minutes} min",
  "说明": "Description",
  "下一步": "Next step",
  "计划日期": "Planned date",
  "预计分钟": "Estimated minutes",
  "估计来源": "Estimate source",
  "所需精力": "Energy required",
  "自动估计": "Automatic estimate",
  "建议分钟": "Suggested minutes",
  "重复步骤": "Repeating steps",
  "收件分类": "Inbox classification",
  "处理去向": "Resolution",
  "相关估计记录": "Related estimate records",
  "已确认变更详情": "Confirmed change details",
  "状态：{status}": "Status: {status}",
  "本机修改已落下，保存确认待完成": "Applied locally; durable-save confirmation pending",
  "已撤销": "Undone",
  "已提交": "Committed",
  "记录同步：{status}": "Record sync: {status}",
  "待同步": "Awaiting sync",
  "撤销：{availability}": "Undo: {availability}",
  "可在协作记录中预览并确认": "Available to preview and confirm in collaboration history",
  "当前不可用": "Currently unavailable",
  "变更内容已移除": "Change details removed",
  "关联{kind}：{id}": "Related {kind}: {id}",
  "重复计划": "repeat schedule",
  "实体": "entity",
  "不可用": "unavailable",
  "在本机核对与撤销": "Review and undo locally",
  "{field}：{before} → {after}": "{field}: {before} → {after}",
  "每轮最多选择 8 条记忆。可以取消一些条目后重新预览。": "Select up to 8 memories per turn. Deselect some items and preview again.",
  "所选记忆正文合计超过 1200 字。没有发送，请减少选择后重新预览。": "Selected memory content exceeds 1,200 characters. Nothing was sent; reduce the selection and preview again.",
  "长期记忆仍关闭，可以先在设置中明确启用。": "Long-term memory is off. You can explicitly enable it in Settings.",
  "本机记忆库暂不可用，已停止引用这些记忆。": "The local memory store is unavailable. These memories are no longer referenced.",
  "对话已经变化，未删除。请重新打开核对后再确认。": "The conversation has changed and was not deleted. Reopen it to review before confirming.",
  "请先核对要删除的这段对话，再确认删除。": "Review the conversation you want to delete, then confirm deletion.",
  "本次临时对话已达到容量。可以继续已有对话，或明确删除不再需要的一段后新建。": "Temporary conversation capacity is full. Continue an existing conversation, or explicitly delete one you no longer need before starting another.",
  "这段对话已按保留期限到期。可以开始新对话。": "This conversation has reached its retention deadline. You can start a new one.",
  "AI 协作还未开启，手动草稿仍可继续编辑。": "AI collaboration is not enabled. You can keep editing the manual draft.",
  "AI 尚未配置好，手动草稿仍可继续编辑。": "AI is not configured yet. You can keep editing the manual draft.",
  "这段对话已不可用，可以开始新对话。": "This conversation is no longer available. You can start a new one.",
  "这段对话需要重新打开。": "This conversation needs to be reopened.",
  "单条最多 8,000 个 Unicode 字符，请拆成几段发送；原文仍在。": "Each message can contain up to 8,000 Unicode characters. Split it into smaller messages; your text is retained.",
  "写点什么再发。": "Write something before sending.",
  "参考范围已失效，请重新打开对话核对。": "The reference scope has expired. Reopen the conversation to review it.",
  "参考范围需要重新确认，请重新打开对话核对。": "The reference scope needs confirmation. Reopen the conversation to review it.",
  "当前任务已变化，草稿未应用。请重新核对任务。": "The current task changed. The draft was not applied; review the task again.",
  "本机保存不可用，内容仍保留在本次运行中。": "Local saving is unavailable. The content remains for this app session.",
  "输入草稿尚未保存，原文仍在；请将过长内容分段后再试。": "The input draft is not saved. Your text remains; split long content into smaller parts and retry.",
  "对话仍保留在本机，参考范围尚未更新。可以重新选择参考内容后再应用。": "The conversation remains locally, but the reference scope has not been updated. Select the reference content again before applying it.",
  "本机保存未成功，内容仍保留在本次运行中。": "Local saving failed. The content remains for this app session.",
  "这台系统暂不支持已验证的迁移备份，旧记录未改写。当前可以仅本次继续。": "This system does not support a verified migration backup. Existing records are unchanged. You can continue for this session only.",
  "本机记录备份未成功，旧记录未改写。当前可以仅本次继续。": "The local record backup failed. Existing records are unchanged. You can continue for this session only.",
  "本机记录的身份文件缺失，现有记录未改写。当前可以仅本次继续。": "The local record identity file is missing. Existing records are unchanged. You can continue for this session only.",
  "本机记录身份需要恢复，现有记录未改写。当前可以仅本次继续。": "The local record identity needs recovery. Existing records are unchanged. You can continue for this session only.",
  "本机记录身份尚未完整保存，现有记录未改写。当前可以仅本次继续。": "The local record identity is not fully saved. Existing records are unchanged. You can continue for this session only.",
  "本机可靠保存暂不可用，内容仅保留在本次运行中。": "Reliable local saving is unavailable. Content is retained only for this app session.",
  "处理中…": "Processing…",
  "本机变更回执": "Local change receipt",
  "只核对提交记录与可用撤销，不开启对话或模型请求": "Review commit records and available undo only; no conversation or model request is started",
  "这次未完成，内容仍在，可以重试或返回手动草稿。": "This did not finish. The content remains; retry or return to the manual draft.",
  "当前输入或草稿选择待保存 · 暂停时保留": "Current input or draft selection awaits saving · Retained when paused",
  "正在读取本机对话…": "Loading the local conversation…",
  "这段对话尚未保存到本机。": "This conversation is not saved locally yet.",
  "记录详情": "Record details",
  "对话": "Conversations",
  "一起理一理": "Let's work through it",
  "正在生成…": "Generating…",
  "{count} / 8,000 字": "{count} / 8,000 characters",
  "本地模板": "Local template",
  "待核对的记忆变更建议": "Memory change suggestion to review",
  "{kind} · 版本 {version}": "{kind} · Version {version}",
  "永久遗忘建议": "Permanent forgetting suggestion",
  "记忆修改建议": "Memory edit suggestion",
  "目标记忆：{id}": "Target memory: {id}",
  "核对原文、关联来源和全部影响范围后，永久遗忘需单独确认，无法撤销。": "Review the original text, linked sources, and full affected scope. Permanent forgetting requires separate confirmation and cannot be undone.",
  "核对当前内容与差异，确认后更新原条目。": "Review the current content and differences. Confirmation updates the original item.",
  "核对记录": "Review record",
  "核对永久遗忘范围": "Review permanent forgetting scope",
  "核对记忆修改": "Review memory changes",
  "待核对的安排建议": "Planning suggestion to review",
  "安排建议 · 版本 {version}": "Planning suggestion · Version {version}",
  "可编辑并单独确认，不改变自评或能量曲线。": "You can edit and confirm this separately. Self-checks and the energy curve are unchanged.",
  "核对安排建议": "Review planning suggestion",
  "待核对的记忆建议": "Memory suggestion to review",
  "记忆建议 · 版本 {version}": "Memory suggestion · Version {version}",
  "内容、范围和有效期确认后才保存。": "Saved only after you confirm the content, scope, and expiry.",
  "核对记忆建议": "Review memory suggestion",
  "变更建议版本 {version}": "Change suggestion version {version}",
  "变更建议 · 版本 {version}": "Change suggestion · Version {version}",
  "{count} 项建议，查看差异后确认。": "{count} suggestions. Review the differences before confirming.",
  "查看变更差异": "View change differences",
  "草稿版本 {version}": "Draft version {version}",
  "草稿 · 版本 {version}": "Draft · Version {version}",
  "下一动作：{action}": "Next action: {action}",
  "已选版本": "Selected version",
  "选择这个版本": "Choose this version",
  "填入当前任务的下一步草稿，确认后保存": "Fill the current task's next-step draft; save after confirmation",
  "填入新任务草稿，可编辑后保存": "Fill the new task draft; edit before saving",
  "建议记录 · 尚无对应提交回执": "Suggestion record · No matching commit receipt yet",
  "提交状态暂不可用": "Commit status unavailable",
  "任务与日常": "Tasks and routines",
  "记忆": "Memory",
  "回执 {receipt}": "Receipt {receipt}",
  "目标 {id}": "Target {id}",
  "提交状态待核对": "Commit status needs checking",
  "时间线待同步": "Timeline awaiting sync",
  "你": "You",
  "AI 伙伴": "AI companion",
  "可以先聊聊，也可以一起找下一步。": "Start with a conversation, or find the next small step together.",
  "第 {start}–{end} 条，共 {count} 条": "{start}–{end} of {count} messages",
  "放进下一步草稿": "Add to next-step draft",
  "尚未保存到本机；内容仍保留在本次运行中": "Not saved locally; retained for this app session",
  "已保存到本机 · {retention}": "Saved locally · {retention}",
  "已固定": "Pinned",
  "{days} 天": "{days} days",
  "仅本次 · 关闭只暂停，退出应用后不保留": "This session only · Closing pauses it; it is not kept after quitting the app",
  "本轮参考字段：{fields}": "Reference fields for this turn: {fields}",
  "仅参考你在这段对话中提供的内容": "Only content you provide in this conversation is referenced",
  "接收模型：{model} · {endpoint}": "Receiving model: {model} · {endpoint}",
  "未提供地址": "No address provided",
  "接收模型：尚未提供模型信息；以发送前的配置为准": "Receiving model: no model information yet; the configuration at send time applies",
  "没有附加上下文": "No additional context",
  "当前任务：{title}": "Current task: {title}",
  "尚未保存": "Not saved yet",
  "保留在本机": "Kept locally",
  "一段对话": "A conversation",
  "当前对话 · ": "Current conversation · ",
  "还没有可继续的对话": "No conversations to resume yet",
  "对话已暂停，输入草稿尚未保存到本机；再次打开仍可继续。": "Conversation paused. The input draft is not saved locally, but you can continue when you reopen it.",
  "暂停保存未确认，输入草稿仍保留在本次运行中。": "Saving while pausing is unconfirmed. The input draft remains for this app session.",
  "参考选择尚未加入本轮预览；更新预览后才可发送。": "Your reference selection is not included in this turn's preview yet. Update the preview before sending.",
  "正在生成，可以取消；输入内容会保留。": "Generating. You can cancel; your input is retained.",
  "本地模板{detail}。": "Local template{detail}.",
  "模型暂不可用": "Model temporarily unavailable",
  "已有草稿可以带回编辑，也可以继续聊。": "A draft is ready to take back and edit, or you can keep talking.",
  "{action}，输入内容仍在。新的参考内容尚未准备好，请重新打开对话后选择。": "{action}. Your input remains. New reference content is not ready yet; reopen the conversation to select it.",
  "正在取消生成，输入内容会保留。": "Cancelling generation. Your input is retained.",
  "取消请求未确认，输入内容仍在；可以关闭暂停。": "Cancellation is unconfirmed. Your input remains; you can close to pause.",
  "正在读取对话列表…": "Loading the conversation list…",
  "本机提交记录可以独立核对；对话已关闭或删除也不会伪造恢复。": "Local commit records can be reviewed independently. A closed or deleted conversation is not recreated.",
  "这段对话已删除。已建立的任务未改动。": "This conversation was deleted. Tasks already created are unchanged.",
  "已选：{counts}": "Selected: {counts}",
  "未选择额外内容": "No additional content selected",
  "原文仅显示前 500 字；发送范围见本轮预览": "Only the first 500 characters are shown; see this turn's preview for the sending scope",
  "不在可选范围内": "Not eligible for selection",
  "暂无可选内容，可搜索或更换类别。": "No selectable content. Search or choose another category.",
  "本机搜索最多 200 字；输入仍在。": "Local search is limited to 200 characters. Your input remains.",
  "本机内容读取未完成，可以重试。": "Local content could not be read. You can retry.",
  "先前生成已取消": "Previous generation cancelled",
  "模式已更改": "Mode changed",
  "旧参考范围已撤回": "Previous reference scope withdrawn",
  "已取消生成，输入内容仍在。": "Generation cancelled. Your input is retained.",
  "本机预览已更新；下次发送才会使用这些内容。": "Local preview updated. This content is used only when you next send.",
  "本机保存列表暂不可用；这里只显示当前运行中的对话。": "The locally saved list is unavailable. Only conversations from this app session are shown.",
  "选择有变，更新预览后才可发送。": "Selection changed. Update the preview before sending.",
  "仅参考已选内容 · 今天": "Only selected content is referenced · Today",
  "长期记忆已关闭，启用后可选择。": "Long-term memory is off. Enable it to select memories.",
  "这类内容暂不可用，不能据此判断没有记录。": "This content type is unavailable. This does not mean there are no records.",
  "每轮最多选择 8 条记忆，正文合计最多 1200 字。": "Select up to 8 memories per turn, with up to 1,200 characters in total.",
  "每类最多选择 50 项，可以先取消一些条目。": "Select up to 50 items per category. Deselect some items first.",
  "：{detail}": ": {detail}",
  "基础餐": "Basic meal",
  "小鱼": "Fish",
  "骨头": "Bone",
  "甜甜圈": "Donut",
  "咖啡": "Coffee",
  "胡萝卜": "Carrot",
  "蘑菇": "Mushroom",
  "饭团": "Rice ball",
  "牛奶": "Milk",
  "浆果": "Berries",
  "蛋糕": "Cake",
  "饱食+{value}": "Fullness +{value}",
  "库存 {count} 份 · 总喂食 {total}": "{count} in stock · Fed {total} times",
  "库存空了 · 伙伴页可用食物券兑换": "No food in stock · Exchange food tickets on the Companion page",
  "上次结果还未核对，刷新失败。再次点击会先核对库存。": "The previous result is still unverified and refresh failed. Click again to check inventory first.",
  "库存已刷新，上次请求已过核对期限。核对后可再次点击。": "Inventory refreshed. The previous request has expired. Check the inventory, then click again.",
  "上次{action}结果尚未确认，再次点击会核对同一请求。": "The previous {action} result is unconfirmed. Click again to check the same request.",
  "现在还不饿，基础餐留到饱食不高于 {value} 时。": "Not hungry yet. Save the basic meal for fullness of {value} or less.",
  "食物券不足，今天首次推进后可获得 {count} 张。": "Not enough food tickets. Make your first progress today to earn {count}.",
  "这次没有完成{action}。": "The {action} did not complete.",
  "兑换": "exchange",
  "这份食物已经没有库存了。": "This food is out of stock.",
  "今天的基础餐已经用完。": "Today's basic meals have been used up.",
  "这份食物的库存已满。": "Inventory for this food is full.",
  "达到对应等级后解锁。": "Unlocks at the required level.",
  "当前请求记录已满，稍后再试。": "The request log is full. Try again later.",
  "请求身份不一致，这次没有执行。": "The request identity did not match. Nothing was executed.",
  "这次请求无效，没有执行。": "This request is invalid. Nothing was executed.",
  "这份食物不可用。": "This food is unavailable.",
  "喂食记录已达到上限。": "The feeding record limit has been reached.",
  "照料记录已达到上限。": "The care record limit has been reached.",
  "专注 · ": "Focus · ",
  "休息 · ": "Break · ",
  "读书": "Reading",
  "打字": "Typing",
  "写文档": "Writing",
  "浏览网页": "Browsing",
  "看行情": "Watching markets",
  "整理便签": "Organizing notes",
  "放空发呆": "Daydreaming",
  "打个小盹": "Napping",
  "慢慢喝茶": "Sipping tea",
  "伸展一下": "Stretching",
  "看看窗外": "Looking outside",
  "照料小苗": "Tending a plant",
  "听音乐": "Listening to music",
  "写代码": "Coding",
  "和 AI 对话": "Talking with AI",
  "{activity}，换一个陪伴动作": "{activity}. Choose another companion activity",
  "{activity}，切换伙伴当前动作": "{activity}. Change the companion's current activity",
  "音乐疗愈中": "Unwinding with music",
  "AI协作中": "Working with AI",
  "音乐": "Music",
  "AI协作": "AI collaboration",
  "编程": "Coding",
  "小步 {name}：点按与按住都是互动，右键打开命令菜单": "bubu {name}: click or hold to interact; right-click to open commands",
  "{summary}，剩余 {time}，打开面板": "{summary}, {time} remaining. Open panel",
  "{summary}，打开面板": "{summary}. Open panel",
  "本轮待确认": "Session awaiting confirmation",
  "关联任务已完成": "Linked task completed",
  "会话需要处理": "Session needs attention",
  "本轮已结束，落点待处理": "Session ended; next step needs attention",
  "相识 {days} 天": "Together for {days} days",
  "今天刚认识": "We met today",
  "{met} · 饱食 {satiation} · 一起吃过 {feeds} 次": "{met} · Fullness {satiation} · Shared {feeds} meals",
  "默契 {points} 点 · 再 {remaining} 点到「{next}」": "Bond {points} · {remaining} more to “{next}”",
  "默契 {points} 点 · 已经是最信任的阶段": "Bond {points} · Highest trust reached",
  "{label}，默契 {points} 点，再 {remaining} 点到{next}": "{label}, bond {points}, {remaining} more to {next}",
  "{label}，默契 {points} 点": "{label}, bond {points}",
  "刚认识": "Just met",
  "慢慢熟了": "Getting acquainted",
  "熟悉了": "Familiar friends",
  "很信任": "Deep trust",
  "和它慢慢熟了": "Getting to know each other",
  "成了熟悉的伙伴": "Becoming close companions",
  "它很信任你了": "Your companion trusts you deeply",
  "已达成": "Reached",
  "还差 {points} 点": "{points} points to go",
  "{count} / {total} 枚纪念": "{count} / {total} keepsakes",
  "食物券 {count} 张": "{count} food tickets",
  "{total} 种 · 已解锁 {count}": "{total} forms · {count} unlocked",
  "暂无可选形态": "No forms available",
  "{count} 枚纪念": "{count} keepsakes",
  "专注 {focus} 次 · 完成 {tasks} 件": "{focus} focus sessions · {tasks} tasks completed",
  "下一枚 · {title}": "Next · {title}",
  "{title}解锁进度": "Unlock progress for {title}",
  "纪念册已集齐，每一次陪伴仍会记在这里。": "Your keepsake album is complete. Every moment together still counts.",
  "打开小信": "Open letter",
  "未解锁 · {percent}%": "Locked · {percent}%",
  "一起吃过 {count} 次": "Shared {count} meals",
  "尝过的口味": "Flavors tasted",
  "常备点心": "Everyday snack",
  "熟悉的味道": "A familiar flavor",
  "初次尝到": "First taste",
  "未尝过": "Not yet tasted",
  "当前形态最爱": "This form's favorite",
  "尝过 {count} 次": "Tasted {count} times",
  "等待初尝": "Waiting for a first taste",
  "库存 {count}": "{count} in stock",
  "已解锁": "Unlocked",
  "LV.{level} 解锁": "Unlocks at LV.{level}",
  "兑换{name}，{count} 张食物券": "Exchange {count} food tickets for {name}",
  "LV.{level}解锁食物": "Food unlocks at LV.{level}",
  "核对上次兑换": "Check previous exchange",
  "{count} 张食物券 · 兑换": "{count} food tickets · Exchange",
  "已解锁 {count} / {total}": "Unlocked {count} / {total}",
  "兑换中…": "Exchanging…",
  "已放入食物袋 · 食物券 {count} 张": "Added to food bag · {count} food tickets",
  "头饰": "Headwear",
  "发饰": "Hair accents",
  "光环": "Aura",
  "颈饰": "Neckwear",
  "背饰": "Backwear",
  "随身": "Bag",
  "鞋子": "Footwear",
  "长耳帽饰": "Long-ear headwear",
  "长耳装饰": "Ear accessories",
  "长耳光环": "Long-ear aura",
  "长耳颈饰": "Long-ear neckwear",
  "长耳披风": "Long-ear capes",
  "长耳挎包": "Long-ear bags",
  "长耳鞋子": "Long-ear footwear",
  "{name}专属": "Exclusive to {name}",
  "未解锁": "Locked",
  "{name}，已佩戴": "{name}, equipped",
  "{name}，未解锁：{reason}": "{name}, locked: {reason}",
  "不戴{slot}": "No {slot}",
  "不戴": "None",
  "还没有可搭配的配饰。升级和解锁皮肤都会往这里添件。": "No accessories yet. Level up and unlock forms to add more.",
  "正戴着 {count} 件": "Accessories worn: {count}",
  "现在什么都没戴": "No accessories on",
  "戴着 {count} 件": "{count} accessories on",
  "什么都没戴": "No accessories",
  "还有 {count} 件待解锁": "{count} accessories still locked",
  "配饰已全部解锁": "All accessories unlocked",
  "搭配参考 · {count} 组": "Outfit ideas · {count} sets",
  "Lv.{level} 解锁": "Unlocks at Lv.{level}",
  "默认皮肤": "Default form",
  "Lv.7 解锁 · 飘落花瓣": "Unlocks at Lv.7 · Falling petals",
  "Lv.6 解锁 · 会发光": "Unlocks at Lv.6 · Glowing",
  "Lv.10 解锁 · 头顶皇冠": "Unlocks at Lv.10 · Crown",
  "Lv.10 解锁 · 像素电路": "Unlocks at Lv.10 · Pixel circuits",
  "默认可用 · 长耳形态与专属动作": "Available by default · Long-ear form and unique movements",
  "{name}，当前形态": "{name}, current form",
  "{name}，未解锁": "{name}, locked",
  "成就解锁": "Achievement unlock",
  "当前形态": "Current form",
  "换成这个形态": "Switch to this form",
  "未解锁 · {detail}": "Locked · {detail}",
  "已解锁 {count}": "{count} unlocked",
  "还没有可选的形态。": "No forms available yet.",
  "当前 {current}/{target}": "Current {current}/{target}",
  "饱食 {value}": "Fullness {value}",
  "得到 {name}，点旁边的喂食按钮给我。": "Received {name}. Use the nearby feed button to share it with me.",
  "小步协作": "Work with bubu",
  "最近对话": "Recent conversations",
  "建议经你确认后生效。": "Suggestions take effect after your confirmation.",
  "来源：经本人确认的小步协作": "Source: work with bubu confirmed by you",
  "小步协作未开启，仍可编辑草稿。": "Work with bubu is not enabled. You can still edit the draft.",
  "想聊点什么？": "What’s on your mind?",
  "未保存 · 退出后清除": "Not saved · Cleared on app exit",
  "本机保存 · {retention}": "Saved locally · {retention}",
  "仅本次 · 退出后清除": "This session · Cleared on app exit",
  "这条消息仍在处理中，尚未再次发送。": "This message is still processing. It has not been sent again.",
  "消息身份不一致，未再次发送。": "The message identity does not match. It has not been sent again.",
  "这条消息已有后续对话，未再次发送。": "There are newer messages. This message has not been sent again.",
  "等待小步回复，可以继续写下一条。": "Waiting for bubu. You can write your next message.",
  "发送状态未确认，内容仍在；重试会先核对这条消息。": "Delivery is unconfirmed. Your message is retained; retry checks its status first.",
  "正在取消回复，消息和草稿会保留。": "Canceling the reply. Your message and draft will be retained.",
  "等待小步回复…": "Waiting for bubu…",
  "回复未完成": "Reply incomplete",
  "这条消息未发送": "Message not sent",
  "发送状态待确认": "Delivery unconfirmed",
  "回复已取消": "Reply canceled",
  "重试这条消息": "Retry this message",
  "有消息待确认，尚未确认保存": "Messages pending confirmation · Saving unconfirmed",
  "已有对话草稿，补充要求仍保留在任务编辑页。": "Your existing conversation draft was kept. Additional instructions are still in the task editor.",
  "对话未打开，新输入仍暂存；重新打开后可继续。": "The conversation could not be opened. Your new draft is retained for the next attempt."

});

