// App-authored task workflow copy. Interpolated user/provider data stays verbatim.
export const TASK_EN = Object.freeze({
  "小步 - 提醒": "bubu - Reminder",
  "小步 - 强提醒": "bubu - Strong reminder",
  "撤销": "Undo",
  "专注中想到别的？先丢这里，不打断": "Something on your mind? Capture it without interrupting focus",
  "脑子里冒出什么，写一句丢进来": "Write down whatever is on your mind",
  "没存上，文字还在，稍后再试一次": "Could not save. Your text is still here. Try again.",
  "收下了，在收件箱里等你处理": "Saved to your inbox for later",
  "没有添加：任务状态已变化，请重试。": "Not added: the task changed. Try again.",
  "已添加一步": "Step added",
  "没能保存，输入内容还在。": "Could not save. Your input is still here.",

  "「{title}」还有 {count} 步没勾。": "“{title}” has {count} unfinished steps.",
  "这次没有完成成功，任务与步骤都保留，请重试。": "Completion failed. Your task and steps are unchanged. Try again.",
  "第 {number} 步标题": "Step {number} title",
  "把第 {number} 步往上移": "Move step {number} up",
  "把第 {number} 步往下移": "Move step {number} down",
  "删除第 {number} 步": "Delete step {number}",
  "第 {number} 步": "Step {number}",
  "每个任务最多 {count} 个步骤": "Up to {count} steps per task",
  "每个任务最多 {count} 个步骤。": "A task can have at most {count} steps.",
  "新加的步骤会先排在末尾；保存之后就能自由调整顺序了。": "New steps go at the end. You can reorder them after saving.",
  "这一次已经跳过，只作为历史保留。": "This occurrence was skipped and is kept as history.",
  "已完成的任务不再修改；需要的话可以再做一遍。": "Completed tasks cannot be edited. You can do the task again.",
  "已安排": "Planned",
  "有开始时间": "Start time set",
  "有截止日期": "Deadline set",
  "有有效期限": "Expiry set",
  "{count} 个标签": "{count} tags",
  "能量、估时、标签": "Energy, estimate and tags",
  "重复：{rule}": "Repeat: {rule}",
  "这件任务已不在列表中，请关闭后重新选择。": "This task is no longer in the list. Close this dialog and choose again.",
  "标题不能为空。想放弃这次修改就按取消。": "A title is required. Choose Cancel to discard these edits.",
  "第 {number} 步还没有标题；要删掉它请按 ✕。": "Step {number} needs a title. Use ✕ to remove it.",
  "请选择这次修改只影响本次，还是同时影响以后。": "Choose whether these edits apply to this occurrence or future occurrences too.",
  "这次没有保存成功。修改仍在输入框里，请检查后重试。": "Saving failed. Your edits are still here. Check them and try again.",
  "每周规则至少选择一个星期。": "Choose at least one day of the week.",
  "未来重复规则已保存；历史和当前这一次没有被回写。": "Future repeat settings saved. History and this occurrence are unchanged.",
  "重复已暂停；当前这一次仍然可以做完。": "Repeats paused. You can still finish this occurrence.",
  "重复已恢复；如果没有开放实例，下一次已经排好。": "Repeats resumed. If none was open, the next occurrence is now ready.",
  "重复已结束；当前这一次仍然可以做完。": "Repeats ended. You can still finish this occurrence.",
  "任务没有保存，输入内容还在。检查日期与重复设置后再试一次。": "Task not saved. Your input is still here. Check dates and repeat settings, then try again.",
  "这一步做什么...": "What will you do in this step…",
  "先写一句要做什么，其他都可以留空。": "Write what you want to do. Everything else is optional.",
  "没有用 AI，所以没替你拆。先写下第一个看得见的动作，比如“打开……”。{detail}": "AI was not used, so no steps were generated. Write the first visible action, such as “Open…”.{detail}",
  "{count} 个步骤": "{count} steps",
  "做完的判断：{criteria}": "Done when: {criteria}",
  "完成标准": "Completion criteria",
  "估时": "Estimate",
  "已按 AI 建议填好：{fields}。每一项都能改或清空，标题没有动。": "Filled from the AI suggestion: {fields}. You can edit or clear every field. The title is unchanged.",
  "这次没有可补的字段，已填内容保持原样。": "There are no fields to fill. Your existing input is unchanged.",
  "先写一句要做什么，伙伴才知道要补什么。": "Write what you want to do so your companion knows what to suggest.",
  "正在补全… {seconds}s": "Filling… {seconds}s",
  "这次没能给出建议，已填的内容都还在。{detail}": "No suggestion was available. All your input is still here.{detail}",
  "这次没能给出建议，已填的内容都还在。": "No suggestion was available. All your input is still here.",
  "AI 正在拆这件事…": "AI is breaking this task down…",
  "正在按通用模板拆…": "Preparing a local template…",
  "正在把任务整理成可以直接开始的小步骤": "Turning this task into small, actionable steps",
  "生成没有完成；任务本身没有变化，你也可以手动加一步。": "Generation did not finish. Your task is unchanged; you can add a step manually.",
  "这次没能生成拆解建议，请稍后重试。": "No breakdown suggestion was generated. Try again later.",
  "这次没能生成拆解建议，任务本身没有变。": "No breakdown suggestion was generated. Your task is unchanged.",
  "Provider 不可用，已安全回退到本地确定性模板（{reason}）。": "The provider is unavailable. A local deterministic template was used ({reason}).",
  "未提供原因": "No reason provided",
  "这份只读建议来自已启用的 API。": "This read-only suggestion came from your enabled API.",
  "这份建议来自本地确定性模板。": "This suggestion came from a local deterministic template.",
  "可选澄清：{question}": "Optional clarification: {question}",
  "至少要留一个步骤，或者按“不用了”关掉。": "Keep at least one step, or choose Cancel.",
  "建议已过期，请关闭后重新生成。": "This suggestion expired. Close it and generate another.",
  "这次没有保存，当前编辑仍然保留。": "Not saved. Your current edits are still here.",
  "本地确定性模板": "Local deterministic template",
  "已启用的 API": "Enabled API",
  "本地规则": "Local rules",
  "密钥被拒（HTTP {status}），检查 API 密钥是否正确、是否过期{detail}": "API key rejected (HTTP {status}). Check that it is valid and has not expired{detail}",
  "这个地址上没有可用接口（HTTP 404），检查 Base URL{detail}": "No API was found at this address (HTTP 404). Check the Base URL{detail}",
  "HTTP 429 限流，稍后再试": "HTTP 429 rate limit. Try again later",
  "HTTP 400，通常是模型名或该密钥授权范围不匹配{detail}": "HTTP 400. Check the model name and API key access{detail}",
  "HTTP 402，账户余额不足{detail}": "HTTP 402. Insufficient account balance{detail}",
  "还没保存 API 密钥": "No API key saved",
  "尚未配置完整的模型连接，本次使用本地回复": "Model connection is incomplete; a local reply was used",
  "还没填模型名": "No model name entered",
  "模型在时限内没回话（超时），本地模板已先填好": "The model timed out; a local template was used",
  "连接超时，模型没在时限内回话": "Connection timed out before the model responded",
  "接口响应不是有效 JSON，检查 Base URL 和服务商兼容协议": "The API response is not valid JSON. Check the Base URL and provider protocol",
  "接口返回了网页，检查 Base URL 是否为 API 地址，或网关是否要求登录": "The API returned a web page. Check the API Base URL and gateway login requirements",
  "接口返回了流式响应，当前请求需要非流式 JSON；检查服务商兼容协议": "The API returned a stream, but this request requires non-streaming JSON. Check the provider protocol",
  "接口返回了空响应，检查 Base URL 和服务商状态": "The API response was empty. Check the Base URL and provider status",
  "模型接口暂不可用，本次使用本地回复": "Model API unavailable; a local reply was used",
  "模型内容未通过校验，本次使用本地回复": "Model output failed validation; a local reply was used",
  "模型返回里没有内容": "The model response contained no output",
  "模型返回过大": "The model response is too large",
  "Base URL 解析到了内网地址，只允许公网 HTTPS": "Base URL resolves to a private address. Only public HTTPS is allowed",
  "Base URL 指向本机或内网主机名，只允许公网 HTTPS": "Base URL points to a local or private hostname. Only public HTTPS is allowed",
  "Base URL 直写了内网 IP，只允许公网 HTTPS": "Base URL contains a private IP. Only public HTTPS is allowed",
  "Base URL 不合法": "Invalid Base URL",
  "只允许 443 端口": "Only port 443 is allowed",
  "请求没成功": "Request failed",
  "（AI 未生效：{reason}）": " (AI was not used: {reason})",
  "每 {count} {unit}": "Every {count} {unit}",
  "天": "days",
  "周": "weeks",
  "月": "months",
  " · 完成后再算": " · After completion",
  "已暂停 · ": "Paused · ",
  "已结束 · ": "Ended · ",
  "专注期间只可加步骤；结束这一轮后再编辑整件任务。": "You can only add steps during focus. Finish this session before editing the task.",
  "这件任务已不在列表中，面板刷新后可以重新选择。": "This task is no longer in the list. Choose again after refreshing.",
  "这件任务已经完成了；需要的话可以再做一遍。": "This task is complete. You can do it again if needed.",
  "这一次已经跳过，下一次已经排好了。": "This occurrence was skipped. The next one is ready.",
  "这一步已经勾过，不需要再勾。": "This step is already complete.",
  "这不是重复任务，没有“这一次”可以跳。": "This task does not repeat, so there is no occurrence to skip.",
  "它的重复规则已不存在，请刷新面板后重试。": "Its repeat rule no longer exists. Refresh and try again.",
  "这个重复系列已经结束；需要继续时请复制成一个新系列。": "This repeat series has ended. Copy it into a new series to continue.",
  "这件任务仍绑定着当前计时，请先结束计时再处理。": "This task is linked to the current timer. End the timer first.",
  "开放中的重复任务不能直接归档；请先完成或跳过这一次。": "Finish or skip this open occurrence before archiving it.",
  "这个任务已经有 100 个步骤，请先整理现有步骤。": "This task has 100 steps. Organize the existing steps first.",
  "请先写下一个具体、可动手的下一步。": "Write a specific, actionable next step first.",
  "这次没有成功，任务内容仍然保留，请重试。": "That did not succeed. Your task is unchanged. Try again.",
  "关联任务已不在列表中；刷新后可改选任务，或选择自由专注。": "The linked task is no longer in the list. Refresh and choose another task, or start free focus.",
  "这件任务已经完成，不能继续计时；可以结束这段。": "This task is complete. You cannot resume its timer, but you can end this session.",
  "先写下一个可观察的下一动作，再开始两分钟。": "Write an observable next action before starting two minutes.",
  "这件任务已到自动失效时间。先在任务列表的“更多”里续期。": "This task has expired. Renew it from More in the task list.",
  "当前计时没有暂停，请按更新后的面板继续。": "This timer is not paused. Continue from the updated panel.",
  "请先完成两分钟启动后的三选一。": "Choose what to do after your two-minute start first.",
  "请先保存或跳过上一轮的落点，再开始新的计时。": "Save or skip the previous session’s restart note before starting another timer.",
  "这一轮已到点，请先确认计入完成或放弃本轮。": "This session ended. Confirm it as complete or discard it first.",
  "这条落点已经处理，可以继续下一步。": "This restart note is already handled. Continue with the next step.",
  "这条落点已经处理或更新，请按当前面板继续。": "This restart note was handled or updated. Continue from the current panel.",
  "这条落点已被更新，请按当前面板继续。": "This restart note was updated. Continue from the current panel.",
  "落点没有保存，输入仍保留，请重试或暂时跳过。": "Restart note not saved. Your input is still here. Try again or skip for now.",
  "这段计时已经在进行或暂停中。": "This timer is already running or paused.",
  "已有另一段计时正在进行或暂停中，请先处理当前计时。": "Another timer is running or paused. Handle it first.",
  "现在没有正在进行的专注，时长会在下一轮生效。": "No focus session is running. This duration applies to the next one.",
  "两分钟救援与休息是固定时长，不可调整。": "Two-minute starts and breaks have fixed durations.",
  "不能缩到已经投入的时长之下；想现在停下请选“结束这段”。": "Duration cannot be shorter than time already spent. Choose End session to stop now.",
  "这次没有启动成功，状态和任务都已保留，请重试。": "The session did not start. Your state and task are unchanged. Try again.",
  "紧迫": "Urgency",
  "能量匹配": "Energy match",
  "时长适配": "Duration fit",
  "易启动": "Ease of starting",
  "下一步清晰": "Clear next step",
  "回避信号": "Avoidance signal",
  "恢复势能": "Resume momentum",
  "今天这次已完成，下次 {date}": "This occurrence is complete. Next: {date}",
  "已撤销，这件事回到待办": "Undone. This task is back in your list.",
  "已经不能撤销了": "This can no longer be undone.",
  "日常记录": "Routine log",
  "情绪": "Feeling",
  "刚做过": "Just did",
  "想养成": "Build a habit",
  "吃饭": "Meal",
  "咖啡 / 茶": "Coffee / tea",
  "用药": "Medication",
  "其他日常": "Other routine",
  "已转任务": "Created task",
  "已安排任务": "Scheduled task",
  "已放以后": "Saved for later",
  "已建日常": "Created routine",
  "已记一次": "Logged once",
  "已记状态": "Recorded energy",
  "已存情绪": "Saved feeling",
  "已留存": "Kept",
  "一件准备去做的事": "Something you plan to do",
  "转为任务": "Make a task",
  "需要重复做的日常，创建后可以设置提醒": "A repeatable routine. You can add reminders after creating it.",
  "建成日常": "Create routine",
  "确认刚做过的事情，记录到所选日常": "Record what you just did in the selected routine",
  "创建「{kind}」并记录一次，不设置提醒": "Create “{kind}” and log it once, without reminders",
  "记录一次": "Log once",
  "创建并记一次": "Create and log",
  "确认后记录当时的能量状态": "Record how your energy felt at that time",
  "确认状态": "Record energy",
  "留一条情绪记录，不自动改变能量": "Save a feeling without changing energy automatically",
  "保存情绪": "Save feeling",
  "保留想法，不创建待办": "Keep this note without creating a task",
  "保存想法": "Save note",
  "选一个类型，或原样留存": "Choose a type, or keep it as written",
  "先留存": "Keep for now",
  "更多收件操作": "More inbox actions",
  "更多操作": "More actions",
  "未保存": "Not saved",
  "已确认": "Confirmed",
  "AI 建议": "AI suggestion",
  "待分类": "Needs a type",
  "记录到": "Log to",
  "选择日常": "Choose a routine",
  "选择类型": "Choose a type",
  "新建名称": "New name",
  "给这件日常起个名字": "Name this routine",
  "当时的能量": "Energy at that time",
  "选择状态": "Choose energy",
  "能量状态 · {level}": "Energy · {level}",
  "待选择": "Not chosen",
  "日常设置 · {kind}": "Routine · {kind}",
  "待选择类型": "Choose a type",
  "这条是": "This is",
  "来源记录仍保留": "Source record retained",
  "删除收件": "Delete capture",
  "删除关联来源": "Delete linked source",
  "下个工作时段": "Next work period",
  "只留存": "Keep only",
  "这条收件已经处理，列表已更新。": "This capture was handled. The list is updated.",
  "分类已改变，请重新确认操作。": "The category changed. Confirm the action again.",
  "先选择日常类型。": "Choose a routine type first.",
  "有多条同类日常，请选择记录到哪一条。": "Several routines match. Choose which one to log.",
  "所选日常已经改变，请重新选择。": "The selected routine changed. Choose again.",
  "请为这件日常填写名称。": "Name this routine first.",
  "日常数量已满，可以先移除不再需要的日常。": "The routine limit is reached. Remove routines you no longer need.",
  "这一天的记录已满，原文仍留在收件箱。": "This day’s log is full. The original stays in the inbox.",
  "这条记录已超过日常打卡的时间范围，可以选择“只留存”。": "This capture is outside the routine logging window. You can keep it instead.",
  "先选择当时的能量状态。": "Choose the energy level at that time.",
  "已有更新的状态记录；这条内容可以选择“只留存”。": "A newer energy record exists. You can keep this capture instead.",
  "确认留存 {count} 条": "Confirm keeping {count} captures",
  "还没有这类历史记录": "No history in this category yet",
  "这个分类下没有待整理的收件": "No pending captures in this category",
  "确认删除这条情绪的全部关联原文": "Confirm deleting all original sources linked to this feeling",
  "正在读取历史记录": "Loading history",
  "部分历史暂不可用，当前显示已读取的记录。": "Some history is unavailable. Previously loaded records are shown.",
  "历史记录暂不可用。": "History is unavailable.",
  "补上这一项后就能保存。": "Fill this field to save.",
  "没有保存成功，原文仍在，请稍后重试。": "Not saved. The original is still here. Try again later.",
  "连接暂时中断，原文仍在，请稍后重试。": "Connection interrupted. The original is still here. Try again later.",
  "已留存 {count} 条，可在历史记录中查看。": "Kept {count} captures. You can find them in history.",
  "{blocker} · 三条出路": "{blocker} · Three options",
  "一个小办法": "One small idea",
  "先选定一件事。": "Choose a task first.",
  "已回退本地模板（{reason}）": "Using a local template ({reason})",
  "这次没生成建议，可以自己写一步。": "No suggestion was generated. You can write a step yourself.",
  "当前任务已变化，这份下一步草稿未保存。": "The current task changed. This next-step draft was not saved.",
  "先写下一个能动手的下一步。": "Write an actionable next step first.",
  "这次没保存成，建议还在输入框里。": "Not saved. The suggestion is still in the input.",
  "这次没能取得建议，可以重试。": "No suggestion was available. Try again.",
  "本地策略建议已关。": "Local strategy suggestions are off.",
  "现在没有合适的。": "No suitable idea right now.",
  "{detail} · 来源：{source}": "{detail} · Source: {source}",
  "已记在本机。": "Recorded on this device.",
  "已记下，不再出现。": "Recorded. This idea will not appear again.",
  "这次没能保存反馈，可以重试。": "Feedback was not saved. Try again.",
  "协作草稿 · 未保存": "Collaboration draft · Not saved",
  "针对这件事的下一步": "A next step for this task",
  "这件事已经不在了。": "This task is no longer available.",
  "这件事已经完成了。": "This task is already complete.",
  "这次已经跳过了。": "This occurrence was skipped.",
  "这件事刚被改过,先看一眼再问会更准。": "This task just changed. Review it before asking again.",
  "本地建议（{reason}）": "Local suggestion ({reason})",
  "本地建议": "Local suggestion",
  "做不动就先做：{action}": "If that feels too much, start with: {action}",
  "正在想一个针对这件事的下一步……下面那条办法可以先看。": "Thinking of a next step for this task… You can read the idea below while you wait.",
  "这次没想出来,先按下面那条办法试试。": "No next step came through. You could try the idea below first.",
  "要不要试试只做眼前能看见的第一个动作？": "Would you like to try just the first visible action?",
  "把目标缩成“打开文件、写下标题”这类可以立刻观察到的动作，做完再决定下一步。": "Make the goal something visible, such as opening a file or writing a heading. Decide what comes next after that.",
  "要不要试试只投入两分钟，到点可以停？": "Would you like to try two minutes? You can stop when the time is up.",
  "先约定一个很短的出口，重点是启动，不要求把整件事做完。": "Choose a short stopping point. The aim is to start, not to finish everything.",
  "要不要试试让伙伴安静陪你完成第一步？": "Would you like your companion to quietly keep you company for the first step?",
  "把陪伴当作环境提示，不需要汇报，也不需要证明效率。": "Let the company be a gentle cue. There is no need to report back or prove your productivity.",
  "要不要试试把冒出来的事先放进收件箱？": "Would you like to put that new thought in the inbox for now?",
  "只记一句，不展开处理；记下之后回到刚才留下的下一步。": "Write one line without working through it. Then return to the next step you left.",
  "要不要试试只清出眼前这一小块工作区？": "Would you like to clear just this small part of your workspace?",
  "不用整理整个环境，只移开当前动作不需要的东西。": "You do not need to tidy everything. Move only what is in the way of the current action.",
  "要不要试试留一句“下次先做什么”？": "Would you like to leave one line about what to do first next time?",
  "在切走前写下一个具体落点，回来时就不用重新回忆整段上下文。": "Write a specific restart point before switching away, so you do not have to reconstruct the context later.",
  "要不要试试把脑中的事项缩成最多三条？": "Would you like to narrow the things on your mind to at most three?",
  "先把其余内容放进收件箱，只让当前动作和两个候选留在眼前。": "Put the rest in the inbox. Keep only the current action and two alternatives in view.",
  "要不要试试先选一个看得见的停止点？": "Would you like to choose a visible stopping point first?",
  "可以用一轮时长或一个具体步骤作为边界，到点再决定继续还是停下。": "Use a short session or one specific step as the boundary. Then decide whether to continue or stop.",
  "要不要试试只在中点看一次剩余时间？": "Would you like to check the remaining time just once, halfway through?",
  "减少反复看钟，同时保留一次调整范围或落点的机会。": "Check the clock less often while keeping one chance to adjust the scope or stopping point.",
  "要不要试试从上次的落点继续，而不是重新规划？": "Would you like to continue from your last restart point instead of planning again?",
  "先照着留下的那一句做；如果已经不合适，再把它改成更小的动作。": "Try the line you left yourself first. If it no longer fits, make it a smaller action.",
  "要不要试试把这次回来只算一次重新启动？": "Would you like to count coming back as a fresh start?",
  "不补偿离开的时间，也不要求追平原计划；重新碰一下任务就算进展。": "There is no need to make up lost time or catch up with the old plan. Touching the task again is progress."
});
