// 图标库：从 src/surfaces/shared/icon-paths.json 生成全部输出，谁也不手写 data URI。
//   npm run icons:build   重新生成
//   npm run icons:check   只检查有没有过期（测试也会跑）
// 输出：
//   - src/surfaces/shared/icons.css                      全部图标；popover 通过 <link> 引用（它的 CSP 有 'self'）
//   - impulse.html / pet.html 里 icons:begin … icons:end  只含该页面用到的图标；保留内联子集，
//     CSP style-src 'self' 'unsafe-inline' 同时允许随包提供的局部 CSS，不允许远程样式
// 用法：元素上写 data-icon="play"，图标画在它的 ::before（用 mask + currentColor，颜色跟着文字走）。
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '../..');
const PATHS_FILE = path.join(ROOT, 'src/surfaces/shared/icon-paths.json');
const CSS_FILE = path.join(ROOT, 'src/surfaces/shared/icons.css');
const INLINE_PAGES = ['src/renderer/impulse.html', 'src/renderer/pet.html'];
const BEGIN = '/* icons:begin */';
const END = '/* icons:end */';

const readPaths = () => JSON.parse(fs.readFileSync(PATHS_FILE, 'utf8'));

function dataUri(inner) {
  const svg = `<svg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 24 24' fill='none' stroke='black' `
    + `stroke-width='1.7' stroke-linecap='round' stroke-linejoin='round'>${inner}</svg>`;
  return `url("data:image/svg+xml,${svg.replace(/</g, '%3C').replace(/>/g, '%3E').replace(/#/g, '%23')}")`;
}

const BASE = `[data-icon]::before {
  content: ""; display: inline-block; flex: none;
  width: 1.2em; height: 1.2em; margin-right: 0.42em; vertical-align: -0.22em;
  background-color: currentColor;
  -webkit-mask: var(--icon) center / contain no-repeat; mask: var(--icon) center / contain no-repeat;
}
[data-icon][data-icon-only]::before, [data-icon][aria-label]:empty::before { margin-right: 0; }`;

function renderIconCss(names, { layer = false } = {}) {
  const all = readPaths();
  const list = (names || Object.keys(all)).filter(name => all[name]).sort();
  const rules = list.map(name => `[data-icon="${name}"] { --icon: ${dataUri(all[name])}; }`);
  const body = [BASE, ...rules].join('\n');
  return layer ? `@layer theme {\n${body.split('\n').map(line => `  ${line}`).join('\n')}\n}\n` : `${body}\n`;
}

const header = '/* GENERATED by tools/icons/build.mjs from icon-paths.json — do not edit by hand. */\n';

function usedIcons(html) {
  return [...new Set([...html.matchAll(/data-icon="([a-z0-9-]+)"/g)].map(match => match[1]))];
}

function injected(html) {
  const start = html.indexOf(BEGIN);
  const end = html.indexOf(END);
  if (start < 0 || end < start) throw new Error('missing icons:begin / icons:end markers');
  const names = usedIcons(html.slice(0, start) + html.slice(end));
  return `${html.slice(0, start + BEGIN.length)}\n${renderIconCss(names)}${html.slice(end)}`;
}

function outputs() {
  const files = new Map([[CSS_FILE, header + renderIconCss(null, { layer: true })]]);
  for (const relative of INLINE_PAGES) {
    const file = path.join(ROOT, relative);
    files.set(file, injected(fs.readFileSync(file, 'utf8')));
  }
  return files;
}

function main(argv = process.argv.slice(2)) {
  const check = argv.includes('--check');
  let stale = 0;
  for (const [file, content] of outputs()) {
    const current = fs.existsSync(file) ? fs.readFileSync(file, 'utf8') : '';
    if (current === content) continue;
    stale += 1;
    if (check) console.error(`stale: ${path.relative(ROOT, file)}`);
    else fs.writeFileSync(file, content);
  }
  if (check && stale) { console.error('run: npm run icons:build'); process.exitCode = 1; }
  else console.log(check ? 'icons are up to date' : `icons written (${stale} file(s) changed)`);
}

if (process.argv[1] && path.resolve(process.argv[1]) === fileURLToPath(import.meta.url)) main();

export { readPaths, renderIconCss, usedIcons, injected, outputs, BEGIN, END, header };
