'use strict';
const { app, BrowserWindow } = require('electron');
const fs = require('node:fs');
const path = require('node:path');
const assert = require('node:assert/strict');
const errors = [];
app.on('browser-window-created', (_, win) => win.webContents.on('console-message', details => {
  if (details.level === 'error') errors.push(details.message);
}));
app.on('browser-window-created', (_, win) => {
  for (const event of ['ready-to-show', 'show', 'hide', 'blur']) win.on(event, () => console.log(event, win.webContents.getURL().split('/').pop()));
});
require('./launch');
const pause = ms => new Promise(resolve => setTimeout(resolve, ms));
const deadline = setTimeout(() => app.exit(1), 60000);
const out = path.resolve(__dirname, '../../dist/capture-refinement');
async function run() {
  fs.mkdirSync(out, { recursive: true });
  const find = name => BrowserWindow.getAllWindows().find(w => w.webContents.getURL().endsWith('/' + name + '.html'));
  const panel = find('popover'); const pet = find('pet');
  const pjs = code => panel.webContents.executeJavaScript(code);
  await pjs("window.imAdhder.updateSettings({motionMode:'full',stimulationMode:'balanced'})");
  await pjs("window.imAdhder.switchSkin('usagi')");
  await pet.webContents.executeJavaScript('window.imAdhder.pet_openPanel()'); await pause(200);
  assert.equal(panel.isMovable(), process.platform !== 'darwin');
  assert.equal(await pjs("getComputedStyle(document.querySelector('.compact-header')).webkitAppRegion"), 'drag');
  await pjs('window.imAdhder.hidePopover()');
  const original = pet.getBounds();
  await pjs('window.imAdhder.openImpulse()');
  await pause(1000);
  const quick = find('impulse'); const js = code => quick.webContents.executeJavaScript(code);
  const shot = async (name, win = quick) => fs.writeFileSync(path.join(out, name + '.png'), (await win.webContents.capturePage()).toPNG());
  console.log('quick diagnostics', { visible: quick.isVisible(), loading: quick.webContents.isLoading(), errors });
  assert.ok(quick.isVisible());
  assert.equal(await js("document.body.dataset.mode"), 'idle');
  assert.equal(await pet.webContents.executeJavaScript('document.body.dataset.notebook'), 'ready');
  assert.notDeepEqual(pet.getBounds(), original);
  await shot('idle'); await shot('pet-notebook', pet);
  await js("document.getElementById('impInput').value='测试任意门记录'; document.getElementById('impulseForm').requestSubmit()");
  await pause(250); await shot('saved');
  assert.equal(await pet.webContents.executeJavaScript('document.body.dataset.notebook'), 'saved');
  await pause(1100); assert.equal(quick.isVisible(), false); assert.deepEqual(pet.getBounds(), original);
  await pjs("(async()=>{const s=await window.imAdhder.getState();const t=s.tasks.find(t=>!t.seriesId&&!t.completed);await window.imAdhder.startPomodoro(t.id,25)})()");
  await pjs('window.imAdhder.openImpulse()'); await pause(900);
  assert.equal(await js('document.body.dataset.mode'), 'active');
  await js("document.getElementById('stepInput').value='追加验证步骤';document.getElementById('appendStepForm').requestSubmit()");
  await pause(250);
  await js("[...document.querySelectorAll('.pending-step')].find(r=>r.textContent.includes('追加验证步骤')).querySelector('.step-edit-button').click()");
  await js("const input=document.querySelector('.step-inline-editor input');input.value='修改后的步骤';input.dispatchEvent(new Event('input',{bubbles:true})); document.querySelector('.step-inline-editor').requestSubmit()");
  await pause(300);
  assert.ok(await js("document.querySelector('#quickSteps').textContent.includes('修改后的步骤')"));
  assert.ok(await js("document.documentElement.scrollWidth<=innerWidth"));
  await shot('active');
  await js("document.querySelector('.quick-step').click()"); await pause(150);
  await js("document.getElementById('btnCompleteQuickTask').click()"); await pause(350);
  assert.equal(await pet.webContents.executeJavaScript('document.body.dataset.notebook'), 'completed');
  await shot('pet-completed', pet);
  await js('window.imAdhder.hideImpulse()'); await pause(800);
  assert.deepEqual(pet.getBounds(), original);
  assert.deepEqual(errors, []);
  console.log(JSON.stringify({ output: out, errors, original, returned: pet.getBounds() }));
}
app.whenReady().then(() => pause(1600)).then(run).then(() => app.exit(0)).catch(error => { console.error(error.stack); app.exit(1); }).finally(() => clearTimeout(deadline));
