'use strict';

// Native layout/interaction verification against launch.js's disposable profile.
const { app, BrowserWindow } = require('electron');
const fs = require('node:fs');
const path = require('node:path');
const assert = require('node:assert/strict');
const output = path.resolve(__dirname, '../../dist/panel-refinement');
const pause = ms => new Promise(resolve => setTimeout(resolve, ms));
const errors = [];
app.on('browser-window-created', (_, window) => {
  window.webContents.on('console-message', details => {
    if (details.level === 'error') errors.push(details.message);
  });
});
require('./launch');
const deadline = setTimeout(() => app.exit(1), 60000);

async function run() {
  fs.mkdirSync(output, { recursive: true });
  const win = BrowserWindow.getAllWindows().find(w => w.webContents.getURL().endsWith('/popover.html'));
  assert.ok(win);
  win.showInactive();
  const js = script => win.webContents.executeJavaScript(script);
  const shot = async name => {
    await pause(280);
    fs.writeFileSync(path.join(output, name + '.png'), (await win.webContents.capturePage()).toPNG());
  };
  await js(`window.bubu.addImpulse('想给阳台上的植物换一个花盆')`);
  await js(`window.bubu.addImpulse('晚点再查一下咖啡豆的配送时间')`);
  await js(`window.bubu.addImpulse('这是一条较长的收件箱消息，需要跨越多行来验证文字完整显示。'.repeat(5))`);
  await js(`document.getElementById('tabToday').click()`);
  const widthsBefore = await js(`[...document.querySelectorAll('.tab-btn')].map(x=>x.getBoundingClientRect().width)`);
  await js(`(() => { const slider=document.getElementById('durationSlider'); slider.value=45;
    slider.dispatchEvent(new Event('input',{bubbles:true})); slider.dispatchEvent(new Event('change',{bubbles:true})); })()`);
  await pause(220);
  assert.equal(await js(`window.bubu.getState().then(s=>s.focusMinutes.chosen)`), 45);
  await shot('today');
  await js("document.getElementById('reviewInbox').open=true");
  assert.ok(await js("(() => { const r=document.querySelector('.review-inbox-panel').getBoundingClientRect(); return r.left>=0 && r.right<=innerWidth && r.bottom<=innerHeight })()"));
  await shot('review-inbox');
  await js("document.getElementById('reviewInbox').open=false");
  assert.notEqual(await js("getComputedStyle(document.querySelector('#btnStartFocus .focus-play')).animationName"), 'none');
  await js(`document.getElementById('tabTasks').click()`);
  const widthsAfter = await js(`[...document.querySelectorAll('.tab-btn')].map(x=>x.getBoundingClientRect().width)`);
  assert.deepEqual(widthsBefore, widthsAfter, 'selecting a tab cannot compress its icon/count');
  assert.equal(await js(`document.querySelectorAll('#todayInboxStrip').length`), 0);
  assert.equal(await js(`getComputedStyle(document.getElementById('inboxStrip')).display !== 'none'`), true);
  const previewBefore = await js("document.getElementById('inboxStripPreview').textContent");
  await js("document.getElementById('inboxNext').click()");
  await pause(300);
  assert.notEqual(await js("document.getElementById('inboxStripPreview').textContent"),previewBefore);
  assert.equal(await js("getComputedStyle(document.getElementById('inboxStripPreview')).overflowY"),'auto');
  assert.equal(await js("document.getElementById('btnSettings').textContent.trim()"),'');
  assert.equal(await js("document.querySelector('#btnSettings .header-glyph').dataset.icon===document.getElementById('settingsTitle').dataset.icon"),true);
  await shot('tasks');
  await js(`(async () => {
    const state=await window.bubu.getState();
    await window.bubu.archiveTask(state.tasks.find(task=>!task.seriesId).id);
    const archive=document.getElementById('archivePanel'); archive.open=true;
    archive.scrollIntoView({block:'end'});
  })()`);
  await shot('archive');
  await js(`document.getElementById('btnOpenTaskCreate').click()`);
  assert.equal(await js(`document.getElementById('taskAdvanced').open`), false);
  assert.equal(await js(`document.getElementById('createStepsBlock').classList.contains('hidden')`), true);
  assert.ok(await js(`document.getElementById('taskCreateConfirm').getBoundingClientRect().bottom < innerHeight`));
  await shot('new-task');
  assert.ok(await js(`(async () => {
    const {gsap}=await import('../../node_modules/gsap/index.js');
    document.getElementById('taskCreateCancel').click();
    document.getElementById('btnOpenTaskCreate').click();
    await new Promise(resolve=>requestAnimationFrame(resolve));
    return gsap.getTweensOf(document.querySelector('#taskCreateMask .modal-body')).length > 0;
  })()`), 'opening the composer runs a bundled GSAP tween');
  await pause(300);
  await js("document.getElementById('taskAdvanced').open=true; document.getElementById('createAddStep').click(); document.querySelector('#createSteps textarea').value='收起桌面杂物'; document.querySelector('#createSteps textarea').dispatchEvent(new Event('input',{bubbles:true}))");
  assert.equal(await js("document.querySelectorAll('#taskAdvanced details').length"),0,'one disclosure level only');
  assert.ok(await js("document.getElementById('taskCreateConfirm').getBoundingClientRect().bottom<innerHeight"));
  await shot('new-task-options');
  await js("document.getElementById('taskAdvanced').open=false");
  await js(`document.getElementById('taskInput').value='整理桌面'; document.getElementById('taskCreateConfirm').click()`);
  await pause(180);
  assert.ok(await js(`window.bubu.getState().then(s=>s.tasks.some(t=>t.title==='整理桌面'))`));
  await js(`document.getElementById('tabRoutines').click()`);
  assert.ok(await js(`document.getElementById('routinesManage').offsetHeight > 0`));
  await js(`document.getElementById('btnNewRoutine').click(); document.getElementById('routineKind').value='custom'; document.getElementById('routineCustomLabel').value='生活'; document.getElementById('routineTitle').value='喝一杯水'; document.getElementById('btnAddRoutine').click()`);
  await pause(180);
  await js(`document.querySelector('#dailyRoutineQuickChips button').click()`);
  await pause(120);
  assert.ok(await js(`document.querySelector('#dailyRoutineRows [data-act="undo"]') !== null`));
  await shot('routines');
  assert.ok(await js(`window.bubu.getState().then(s=>s.routines.items.some(t=>t.title==='喝一杯水'))`));
  await js(`document.getElementById('tabToday').click(); if(document.getElementById('energyStrip').hidden)document.getElementById('tileEnergy').click(); document.getElementById('moodDock').scrollIntoView({block:'center'})`);
  const dockPoints = await js(`[...document.querySelectorAll('.energy-checkin-btn')].map(b=>{const r=b.getBoundingClientRect();return {x:Math.round(r.x+r.width/2),y:Math.round(r.y+r.height/2)}})`);
  win.webContents.sendInputEvent({type:'mouseMove',...dockPoints[1]});
  win.webContents.sendInputEvent({type:'mouseDown',button:'left',clickCount:1,...dockPoints[1]});
  win.webContents.sendInputEvent({type:'mouseMove',...dockPoints[4]});
  await shot('mood-dock');
  win.webContents.sendInputEvent({type:'mouseUp',button:'left',clickCount:1,...dockPoints[4]});
  await pause(180);
  await js(`document.getElementById('routinesStrip').scrollIntoView({block:'end'})`);
  await shot('today-routines');
  await js(`document.getElementById('tabProgress').click()`);
  await pause(100);
  const stableHeight = await js(`document.getElementById('heatmapTip').offsetHeight`);
  await js(`document.querySelector('.hm-cell').dispatchEvent(new Event('mouseenter'))`);
  assert.equal(await js(`document.getElementById('heatmapTip').offsetHeight`), stableHeight);
  await shot('progress');
  await js("document.querySelector('.hm-cell').click()");
  const heatCell=await js("(() => { const c=document.querySelector('.hm-cell.selected'),r=c.getBoundingClientRect();return {x:Math.round(r.x+r.width/2),y:Math.round(r.y+r.height/2),width:r.width};})()");
  win.webContents.sendInputEvent({type:'mouseMove',x:heatCell.x,y:heatCell.y});
  await pause(150);
  assert.equal(await js("document.querySelector('.hm-cell.selected').getBoundingClientRect().width"),heatCell.width);
  assert.ok(await js("getComputedStyle(document.querySelector('.hm-cell.selected')).boxShadow.includes('inset')"));
  await js("document.getElementById('timelineDay').scrollIntoView({block:'end'})");
  await shot('progress-timeline');
  await js(`document.getElementById('panelTasks').scrollTop=0`);
  await js(`document.getElementById('btnSettings').click()`);
  await shot('settings');
  await js(`document.getElementById('btnSettingsClose').click()`);
  await js(`document.getElementById('btnSettings').click();
    const group=document.querySelector('[data-toggle="aiClarifyEnabled"]').closest('.setting-group');
    group.open=true; group.scrollIntoView({block:'start'});`);
  await pause(100);
  const clarifyBefore = await js(`window.bubu.getState().then(s=>s.settings.aiClarifyEnabled)`);
  await js(`document.querySelector('[data-toggle="aiClarifyEnabled"]').click()`);
  await pause(100);
  assert.equal(await js(`window.bubu.getState().then(s=>s.settings.aiClarifyEnabled)`), !clarifyBefore);
  await js(`const model=document.getElementById('aiModelInput'); model.value='demo-model'; model.dispatchEvent(new Event('input',{bubbles:true}));`);
  assert.equal(await js(`document.getElementById('aiConfigStatus').dataset.state`), 'dirty');
  await js(`document.getElementById('aiSaveConfig').click()`);
  await pause(220);
  assert.equal(await js(`window.bubu.getState().then(s=>s.settings.aiModel)`), 'demo-model');
  assert.equal(await js(`document.getElementById('aiConfigStatus').dataset.state`), 'saved');
  await shot('settings-ai');
  await js(`document.getElementById('btnSettingsClose').click(); document.getElementById('tabToday').click();`);
  await pause(100);
  await js(`document.getElementById('btnStartFocus').click()`);
  await pause(180);
  assert.equal(await js(`document.body.dataset.session`), 'focus');
  assert.equal(await js(`document.getElementById('nowCardTitle').textContent`), '整理桌面');
  const timer = await js(`(() => { const ring=document.querySelector('.focus-orbit').getBoundingClientRect();
    return {width:ring.width,height:ring.height,offset:Number(document.getElementById('focusOrbit').style.strokeDashoffset)}; })()`);
  assert.ok(Math.abs(timer.width - timer.height) < 0.01);
  assert.ok(timer.width >= 200 && timer.offset >= 0 && timer.offset <= 100);
  assert.ok(await js("document.getElementById('btnEditNowTask').classList.contains('hidden')"));
  assert.ok(await js("!document.getElementById('btnAddSessionStep').classList.contains('hidden')"));
  await js("document.getElementById('btnAddSessionStep').click(); document.getElementById('sessionStepInput').value='整理过程中发现的附件'; document.getElementById('sessionStepForm').requestSubmit()");
  await pause(150);
  assert.ok(await js("window.bubu.getState().then(s=>s.tasks.find(t=>t.title==='整理桌面').steps.some(step=>step.title==='整理过程中发现的附件'))"));
  await shot('focus');
  await js(`document.getElementById('btnPauseFocus').click()`);
  await pause(100);
  assert.equal(await js(`document.body.dataset.session`), 'paused');
  assert.equal(await js(`document.documentElement.scrollWidth <= innerWidth`), true);
  await js(`document.body.dataset.motion='reduced'; document.getElementById('tabTasks').click(); document.getElementById('btnOpenTaskCreate').click()`);
  assert.equal(await js(`getComputedStyle(document.querySelector('#taskCreateMask .modal')).animationName`), 'none');
  assert.equal(await js(`import('../../node_modules/gsap/index.js').then(({gsap})=>gsap.getTweensOf(document.querySelector('#taskCreateMask .modal-body')).length)`), 0);
  const fullSize = win.getSize();
  win.setResizable(true);
  win.setMinimumSize(360, 400);
  win.setSize(460, 680);
  await pause(160);
  assert.ok(await js(`innerWidth <= 460`), 'narrow viewport was actually applied');
  assert.ok(await js(`document.getElementById('taskCreateConfirm').getBoundingClientRect().bottom <= innerHeight`));
  assert.ok(await js(`document.documentElement.scrollWidth <= innerWidth`));
  await shot('new-task-narrow');
  await js(`document.getElementById('taskCreateCancel').click(); document.getElementById('tabRoutines').click()`);
  assert.ok(await js(`[...document.querySelectorAll('.tab-btn')].every(b=>b.scrollWidth <= b.clientWidth)`));
  await shot('daily-narrow');
  const petWindow = BrowserWindow.getAllWindows().find(w=>w.webContents.getURL().endsWith('/pet.html'));
  const fed = await petWindow.webContents.executeJavaScript("window.bubu.pet_feed('fish')");
  assert.ok(fed.ok);
  await pause(200);
  await js("document.getElementById('tabCompanion').click()");
  await pause(150);
  assert.ok(await js("document.querySelectorAll('.journey-card').length===8"));
  await js("document.getElementById('journeyAlbum').scrollIntoView({block:'start'})");
  await shot('companion-journey-narrow');
  win.setSize(...fullSize);
  await js("document.getElementById('journeyAlbum').scrollIntoView({block:'start'})");
  assert.ok(await js("document.querySelector('[data-chapter=first-table]') !== null"));
  await js("document.querySelector('[data-chapter=first-table]').open=true");
  await shot('companion-journey');
  assert.deepEqual(errors, []);
  console.log(JSON.stringify({output, timer, widthsBefore, widthsAfter, errors}));
}
app.whenReady().then(() => pause(2000)).then(run).then(() => app.quit()).catch(error => {
  console.error(error.stack); app.exit(1);
}).finally(() => clearTimeout(deadline));
