import fs from 'node:fs';
import path from 'node:path';
import crypto from 'node:crypto';
import { fileURLToPath, pathToFileURL } from 'node:url';
import { collectRasterSprites, validateRasterManifest } from '../../src/capabilities/companion/presentation/raster/schema.mjs';
import { TOOL_SPRITES } from '../../src/content/companion/dango-tools.mjs';
import { PET_APPEARANCE_ITEMS } from '../../src/content/appearance.mjs';
import { EYE_FALLBACKS, MOUTH_FALLBACKS } from '../../src/capabilities/companion/presentation/rig/face.mjs';
import { PET_ACTIONS } from '../../src/content/behaviors.mjs';
import { SESSION_ACTIVITIES } from '../../src/content/session-activities.mjs';
import { sampleActivityStory } from '../../src/capabilities/companion/presentation/activity-playback.mjs';
import { sampleVectorAction } from '../../src/core/pet-action-vector.mjs';
import { resolveDangoView } from '../../src/core/dango-view-policy.mjs';
import { RASTER_PARTICLE_TYPES } from '../../src/capabilities/companion/presentation/dango-raster-particles.mjs';
import { sceneCoverage } from '../../src/capabilities/companion/presentation/dango-raster-scenes.mjs';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '../..');
const assetRoot = path.join(root, 'assets/companion/dango/raster');
const specs = path.join(assetRoot, 'source-specs');
const argument = name => process.argv.find(value => value.startsWith(`--${name}=`))?.slice(name.length + 3);
const fragments = Object.fromEntries(['body', 'tools', 'effects', 'wardrobe', 'scenes'].map(name => {
  const input = argument(name) || path.join(specs, `${name}.json`);
  const data = JSON.parse(fs.readFileSync(input, 'utf8'));
  if (data.complete === false) throw new Error(`${name} fragment is explicitly incomplete`);
  return [name, data];
}));
const manifest = { ...fragments.body, tools: fragments.tools.tools, effects: fragments.effects.effects,
  appearance: fragments.wardrobe.appearance, scenes: fragments.scenes.scenes,
  sessionScenes: fragments.scenes.sessionScenes,
  sceneParticles: { ...fragments.effects.sceneParticles, ...fragments.scenes.sceneParticles } };
const sourceVersions = Object.fromEntries(Object.entries(fragments).map(([name, value]) => [name, value.version || 1]));
manifest.baseUrl = pathToFileURL(`${assetRoot}/`).href;
validateRasterManifest(manifest);
const missing = [];
for (const key of Object.keys(TOOL_SPRITES)) if (!manifest.tools?.[key]) missing.push(`tools/${key}`);
for (const item of PET_APPEARANCE_ITEMS.filter(item => (item.formId || 'dango') === 'dango')) {
  for (const view of ['front', 'three-quarter', 'back']) if (!manifest.appearance?.[item.renderKey]?.views?.[view]) missing.push(`appearance/${item.renderKey}/${view}`);
}
for (const [view, data] of Object.entries(manifest.views)) {
  if (view === 'back') continue;
  for (const eye of Object.keys(EYE_FALLBACKS)) if (!data.face.eyes[eye]) missing.push(`${view}/eyes/${eye}`);
  for (const mouth of Object.keys(MOUTH_FALLBACKS)) if (!data.face.mouth[mouth]) missing.push(`${view}/mouth/${mouth}`);
}
const effects = new Set(['sleep-zzz', 'drowsy-zzz', 'glint', 'hungry', 'coffee', 'ribbon',
  ...RASTER_PARTICLE_TYPES.map(type => `particle-${type}`)]);
for (const original of Object.values({ ...PET_ACTIONS, ...SESSION_ACTIVITIES })) for (let frame = 0; frame <= 20; frame++) {
  const sample = sampleActivityStory(original, frame / 20), view = resolveDangoView('auto', { action: sample.action });
  for (const detail of sampleVectorAction(sample.action, sample.progress, view).details) effects.add(detail.type);
}
for (const key of effects) if (!manifest.effects?.[key]) missing.push(`effects/${key}`);
const scene = sceneCoverage(manifest);
missing.push(...scene.missingScenes.map(key => `scenes/${key}`), ...scene.missingRooms.map(key => `sessionScenes/${key}`),
  ...scene.missingParticles.map(key => `sceneParticles/${key}`));
if (missing.length) throw new Error(`incomplete production art: ${missing.join(', ')}`);
const sources = [...new Set(collectRasterSprites(manifest).map(sprite => sprite.src))].sort();
const assetHashes = Object.fromEntries(sources.map(src => [src,
  crypto.createHash('sha256').update(fs.readFileSync(path.join(assetRoot, src))).digest('hex')]));
delete manifest.baseUrl;
const digest = crypto.createHash('sha256').update(JSON.stringify({ manifest, assetHashes })).digest('hex');
manifest.version = Number.parseInt(digest.slice(0, 8), 16) || 1;
manifest.provenance = { ...manifest.provenance, sourceVersions, assetDigest: digest, assetHashes };
const output = path.resolve(argument('out') || path.join(assetRoot, 'dango.raster.mjs'));
const text = `// Generated by tools/dango-raster/assemble.mjs. Raster sources retain independent provenance.\n`
  + `const freeze = value => { if (value && typeof value === 'object') { Object.values(value).forEach(freeze); Object.freeze(value); } return value; };\n`
  + `const data = ${JSON.stringify(manifest, null, 2)};\n`
  + `data.baseUrl = new URL('./', import.meta.url).href;\nexport const DANGO_RASTER = freeze(data);\n`;
const check = process.argv.includes('--check');
if (check) {
  if (!fs.existsSync(output) || fs.readFileSync(output, 'utf8') !== text) throw new Error(`stale raster manifest: ${output}`);
} else {
  fs.mkdirSync(path.dirname(output), { recursive: true });
  fs.writeFileSync(output, text);
  fs.mkdirSync(specs, { recursive: true });
  for (const [name, data] of Object.entries(fragments)) fs.writeFileSync(path.join(specs, `${name}.json`), `${JSON.stringify(data, null, 2)}\n`);
}
console.log(JSON.stringify({ output, sources: sources.length, version: manifest.version, assetDigest: digest, complete: true, check }, null, 2));
