const { contextBridge, ipcRenderer } = require('electron');

contextBridge.exposeInMainWorld('imAdhder', {
  getState: () => ipcRenderer.invoke('state:get'),
  onPopoverHidden: callback => {
    if (typeof callback !== 'function') throw new TypeError('popover callback required');
    const listener = () => callback();
    ipcRenderer.on('popover:hidden', listener);
    return () => ipcRenderer.removeListener('popover:hidden', listener);
  },
  onStateDiff: (callback) => {
    const listener = (_event, payload) => callback(payload);
    ipcRenderer.on('state:diff', listener);
    return () => ipcRenderer.removeListener('state:diff', listener);
  },

  addTask: task => ipcRenderer.invoke('tasks:add', task),
  completeTask: (id, options) => ipcRenderer.invoke('tasks:complete', {
    id,
    confirmUnfinishedSteps: Boolean(options && options.confirmUnfinishedSteps)
  }),
  completeStep: (taskId, stepId) => ipcRenderer.invoke('tasks:complete-step', { taskId, stepId }),
  skipOccurrence: id => ipcRenderer.invoke('tasks:skip-occurrence', { id }),
  duplicateTask: id => ipcRenderer.invoke('tasks:duplicate', { id }),
  deleteTask: id => ipcRenderer.invoke('tasks:delete', id),
  archiveTask: id => ipcRenderer.invoke('tasks:archive', id),
  restoreTask: id => ipcRenderer.invoke('tasks:restore', id),
  updateTask: (id, patch, scope) => ipcRenderer.invoke('tasks:update', { id, patch, scope }),
  updateSeries: (seriesId, patch) => ipcRenderer.invoke('series:update', { seriesId, ...(patch || {}) }),
  renewTask: (id, expiresAt) => ipcRenderer.invoke('tasks:renew', { id, expiresAt: expiresAt || null }),
  setNowTask: id => ipcRenderer.invoke('tasks:set-now', id),
  clarifyNowTask: (taskId, patch) => ipcRenderer.invoke('tasks:clarify-now', { taskId, ...patch }),
  pickOneTask: options => ipcRenderer.invoke('tasks:pickOne', options || {}),
  previewBreakdown: title => ipcRenderer.invoke('tasks:preview-breakdown', title),
  addWithBreakdown: payload => ipcRenderer.invoke('tasks:add-with-breakdown', payload),
  previewAiBreakdown: payload => ipcRenderer.invoke('ai:preview-breakdown', payload),
  dismissBreakdownProposal: proposalId => ipcRenderer.invoke('tasks:dismiss-proposal', { proposalId }),
  previewEnrich: payload => ipcRenderer.invoke('ai:preview-enrich', payload),
  cancelAiRequests: () => ipcRenderer.invoke('ai:cancel'),
  suggestUnstick: payload => ipcRenderer.invoke('ai:suggest-unstick', payload),
  // 不传 conversationId 就是开一段新对话。渲染层不自己生成会话 id，因为「这段对话
  // 属于谁」只能由主进程按 sender 判定。
  startConversation: payload => ipcRenderer.invoke('ai:conversation-start', payload),
  listConversations: payload => ipcRenderer.invoke('ai:conversation-list', payload),
  getConversation: payload => ipcRenderer.invoke('ai:conversation-open', payload),
  setConversationScope: payload => ipcRenderer.invoke('ai:conversation-scope', payload),
  getConversationContextChoices: payload => ipcRenderer.invoke('ai:conversation-context-choices', payload),
  previewConversationChanges: payload => ipcRenderer.invoke('ai:change-preview', payload),
  confirmConversationChanges: payload => ipcRenderer.invoke('ai:change-confirm', payload),
  cancelConversationChanges: payload => ipcRenderer.invoke('ai:change-cancel', payload),
  getChangeReceipt: payload => ipcRenderer.invoke('ai:change-receipt', payload),
  getConversationReceipts: payload => ipcRenderer.invoke('ai:conversation-receipts', payload),
  getConversationProposalStatus: payload => ipcRenderer.invoke('ai:conversation-proposal-status', payload),
  previewChangeUndo: payload => ipcRenderer.invoke('ai:change-undo-preview', payload),
  setConversationMode: payload => ipcRenderer.invoke('ai:conversation-mode', payload),
  conversationTurn: payload => ipcRenderer.invoke('ai:conversation-turn', payload),
  pauseConversation: payload => ipcRenderer.invoke('ai:conversation-pause', payload),
  cancelConversation: payload => ipcRenderer.invoke('ai:conversation-cancel', payload),
  setConversationRetention: payload => ipcRenderer.invoke('ai:conversation-retention', payload),
  deleteConversation: payload => ipcRenderer.invoke('ai:conversation-delete', payload),
  draftTurn: (message, conversationId) => ipcRenderer.invoke('ai:draft-turn', {
    message, conversationId: conversationId || null
  }),
  discardDraft: conversationId => ipcRenderer.invoke('ai:draft-discard', { conversationId }),
  applyBreakdownProposal: (proposalId, steps, options) => ipcRenderer.invoke('tasks:apply-proposal', {
    proposalId,
    steps,
    targetTaskId: (options && options.targetTaskId) || null,
    scope: (options && options.scope) || undefined
  }),
  getAiCredentialStatus: () => ipcRenderer.invoke('ai:credential-status'),
  importAiCredential: () => ipcRenderer.invoke('ai:credential-import'),
  saveAiCredential: secret => ipcRenderer.invoke('ai:credential-import', { secret }),
  clearAiCredential: () => ipcRenderer.invoke('ai:clear-credential'),
  requestStrategy: (phase, taskId) => ipcRenderer.invoke('strategy:request', { phase, taskId: taskId || null }),
  sendStrategyFeedback: (strategyId, helpful) => ipcRenderer.invoke('strategy:feedback', { strategyId, helpful }),
  openReview: id => ipcRenderer.invoke('reviews:open', { id }),
  resolveReview: (id, action, options) => ipcRenderer.invoke('reviews:resolve', { id, action, ...(options || {}) }),
  listHistory: options => ipcRenderer.invoke('history:list', options || {}),
  getUpdateStatus: () => ipcRenderer.invoke('updates:get'),
  checkForUpdates: () => ipcRenderer.invoke('updates:check'),
  downloadUpdate: () => ipcRenderer.invoke('updates:download'),
  cancelUpdate: () => ipcRenderer.invoke('updates:cancel'),
  installUpdate: () => ipcRenderer.invoke('updates:install'),
  dismissNotice: id => ipcRenderer.invoke('notices:dismiss', { id }),

  startPomodoro: (taskId, minutes) => ipcRenderer.invoke('pomodoro:start', { taskId, minutes }),
  kickstart: (taskId, clarification) => ipcRenderer.invoke('pomodoro:kickstart', { ...clarification, taskId }),
  stopPomodoro: action => ipcRenderer.invoke('pomodoro:stop', action),
  pausePomodoro: () => ipcRenderer.invoke('pomodoro:pause'),
  resumePomodoro: action => ipcRenderer.invoke('pomodoro:resume', action),
  adjustPomodoroDuration: minutes => ipcRenderer.invoke('pomodoro:adjust-duration', { minutes }),
  resolveQuickStart: decision => ipcRenderer.invoke('pomodoro:resolve-quick-start', decision),
  resolveFocusLanding: decision => ipcRenderer.invoke('pomodoro:resolve-focus-landing', decision),

  addImpulse: text => ipcRenderer.invoke('impulses:add', text),
  openImpulse: () => ipcRenderer.invoke('impulse:open'),
  promoteImpulse: id => ipcRenderer.invoke('impulses:promote', id),
  deleteImpulse: id => ipcRenderer.invoke('impulses:delete', id),
  reviewImpulse: (id, action) => ipcRenderer.invoke('impulses:review', { id, action }),
  organizeImpulse: payload => ipcRenderer.invoke('impulses:organize', payload),
  getInboxHistory: options => ipcRenderer.invoke('impulses:history', options),
  keepAllImpulses: ids => ipcRenderer.invoke('impulses:keep-all', { ids }),
  copyAgentPluginCommand: tool => ipcRenderer.invoke('activity:copy-plugin-command', { tool }),

  updateEnergyCheckIn: checkIn => ipcRenderer.invoke('energy:check-in', checkIn),
  setWakeTime: minutes => ipcRenderer.invoke('energy:set-wake', { minutes }),
  keepMoodNote: impulseId => ipcRenderer.invoke('impulses:keep-mood', impulseId),
  deleteMoodNote: id => ipcRenderer.invoke('mood:delete', id),
  undoComplete: token => ipcRenderer.invoke('tasks:undo-complete', token),
  adjustEnergy: direction => ipcRenderer.invoke('energy:adjust', { direction }),
  resetEnergyCalibration: () => ipcRenderer.invoke('energy:reset-calibration'),
  getPlanningGuidance: () => ipcRenderer.invoke('planning:get'),
  cancelPlanningPreview: payload => ipcRenderer.invoke('planning:preview-cancel', payload),
  previewPlanningProposal: payload => ipcRenderer.invoke('planning:proposal-preview', payload),
  previewPlanningPreference: payload => ipcRenderer.invoke('planning:preference-preview', payload),
  confirmPlanningPreference: payload => ipcRenderer.invoke('planning:preference-confirm', payload),
  undoPlanningPreference: payload => ipcRenderer.invoke('planning:preference-undo', payload),
  previewEnergyHistoryConsent: payload => ipcRenderer.invoke('planning:history-preview', payload),
  confirmEnergyHistoryConsent: payload => ipcRenderer.invoke('planning:history-confirm', payload),
  previewEnergyCurveTrial: payload => ipcRenderer.invoke('planning:trial-preview', payload),
  confirmEnergyCurveTrial: payload => ipcRenderer.invoke('planning:trial-confirm', payload),
  undoEnergyCurveTrial: payload => ipcRenderer.invoke('planning:trial-undo', payload),
  updateSettings: patch => ipcRenderer.invoke('settings:update', patch),
  describeQuickPanelShortcut: () => ipcRenderer.invoke('quickPanel:describeShortcut'),
  listMemories: payload => ipcRenderer.invoke('memory:list', payload),
  previewMemoryChange: payload => ipcRenderer.invoke('memory:change-preview', payload),
  confirmMemoryChange: payload => ipcRenderer.invoke('memory:change-confirm', payload),
  previewMemoryUndo: payload => ipcRenderer.invoke('memory:undo-preview', payload),
  getMemoryReceipt: payload => ipcRenderer.invoke('memory:receipt', payload),
  cancelMemoryChange: payload => ipcRenderer.invoke('memory:change-cancel', payload),
  previewMemoryProposal: payload => ipcRenderer.invoke('memory:proposal-preview', payload),
  forgetMemory: memoryId => ipcRenderer.invoke('memory:forget', { memoryId }),
  clearMemories: () => ipcRenderer.invoke('memory:clear'),
  rememberMemory: entry => ipcRenderer.invoke('memory:remember', entry),
  getTimelineDay: dayKey => ipcRenderer.invoke('timeline:getDay', { dayKey }),
  addRoutine: draft => ipcRenderer.invoke('routines:add', draft),
  updateRoutine: (routineId, patch) => ipcRenderer.invoke('routines:update', { routineId, patch }),
  removeRoutine: routineId => ipcRenderer.invoke('routines:remove', { routineId }),
  logRoutine: entry => ipcRenderer.invoke('routines:log', entry),
  undoRoutineLog: occurrenceId => ipcRenderer.invoke('routines:undo-log', { occurrenceId }),
  switchSkin: skinId => ipcRenderer.invoke('skin:switch', skinId),
  equipAppearance: (group, itemId) => ipcRenderer.invoke('appearance:equip', { group, itemId }),
  resetAppearance: () => ipcRenderer.invoke('appearance:reset'),
  buyFood: request => ipcRenderer.invoke('pet:buy-food', request),
  testNudge: (kind, level) => ipcRenderer.invoke('nudge:test', { kind, level }),
  hidePopover: () => ipcRenderer.invoke('window:hide')
});
